<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Close</name>
   <tag></tag>
   <elementGuidId>e94bb078-7b57-4f04-a458-138eae0274cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.rwCloseButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>071e6b8e-4485-471b-8348-e6e65905ffa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>23cedebd-9d5f-4251-b42b-f72c5a51bce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rwCloseButton</value>
      <webElementGuid>ea2a92eb-548a-4d74-a004-0af07d67b025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>1c110a60-e47e-4ce8-9267-3fba2fc58df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>24f87ef8-c503-4ef1-a13f-14be11d8cc7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RadWindowWrapper_ctl00_RadWindowTagInfo&quot;)/table[@class=&quot;rwTable&quot;]/tbody[1]/tr[@class=&quot;rwTitleRow&quot;]/td[@class=&quot;rwTitlebar&quot;]/table[@class=&quot;rwTitlebarControls&quot;]/tbody[1]/tr[1]/td[3]/ul[@class=&quot;rwControlButtons&quot;]/li[1]/a[@class=&quot;rwCloseButton&quot;]</value>
      <webElementGuid>41a209bb-8cb7-4df6-aae0-1669d181dc91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RadWindowWrapper_ctl00_RadWindowTagInfo']/table/tbody/tr/td[2]/table/tbody/tr/td[3]/ul/li/a</value>
      <webElementGuid>038983aa-96e2-46af-89f8-39b05d5a0fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tag Information'])[1]/following::a[1]</value>
      <webElementGuid>4ffa0dba-5494-4109-90cf-09dd96f22b4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='status label'])[1]/following::a[2]</value>
      <webElementGuid>7c20330d-85fe-452d-b630-dfde1d8fe001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='status label'])[2]/preceding::a[1]</value>
      <webElementGuid>8e1f454c-8d34-4d06-bb48-4aa1fd26d604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0);')]</value>
      <webElementGuid>c54d3931-a5e3-4e8f-a07e-35fdc201cca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>ae5c406b-f694-48f3-bf5c-4921365d9616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @title = 'Close' and (text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>a9dbf90a-15c6-4fe4-9f33-7027d8554d51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
