<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Close</name>
   <tag></tag>
   <elementGuidId>3939762f-460c-4660-9c1f-73d479bb9f3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.rwCloseButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='RadWindowWrapper_ctl00_RadWindowSettings']/table/tbody/tr/td[2]/table/tbody/tr/td[3]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1aa4b34e-0ee9-4278-a0dd-57a395a714d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>bab6c983-49b8-4938-b216-69b459455125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rwCloseButton</value>
      <webElementGuid>870a03fd-80b1-41c4-851c-869d3aae2411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>62e7c0ad-c6b9-4528-bd8b-4bbd19729823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>a172f42c-cbc3-4bc8-81e9-cb6a3c30e3ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RadWindowWrapper_ctl00_RadWindowSettings&quot;)/table[@class=&quot;rwTable&quot;]/tbody[1]/tr[@class=&quot;rwTitleRow&quot;]/td[@class=&quot;rwTitlebar&quot;]/table[@class=&quot;rwTitlebarControls&quot;]/tbody[1]/tr[1]/td[3]/ul[@class=&quot;rwControlButtons&quot;]/li[1]/a[@class=&quot;rwCloseButton&quot;]</value>
      <webElementGuid>116657fa-caf4-4e96-8783-39841280b7c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RadWindowWrapper_ctl00_RadWindowSettings']/table/tbody/tr/td[2]/table/tbody/tr/td[3]/ul/li/a</value>
      <webElementGuid>186feab8-fa31-4027-9845-c07834169e97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage District Settings'])[1]/following::a[1]</value>
      <webElementGuid>fedbcc5f-7468-451e-ace8-b20fc828601c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='status label'])[1]/preceding::a[1]</value>
      <webElementGuid>bbb8df86-0622-450b-8063-e3bfb977b2ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0);')]</value>
      <webElementGuid>c40052c4-a081-4caf-8c97-00ca299edbd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>a9939076-ec09-4119-b7ce-a2e024b22c11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @title = 'Close' and (text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>1fbc2162-b500-49ed-a987-c4bb2823c5d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
