<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_District Settings</name>
   <tag></tag>
   <elementGuidId>2be007e7-aaeb-4863-b3ea-7e3cc4eee2e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_LinkButtonDistrictSettings</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_LinkButtonDistrictSettings']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>76ad4177-721e-4f15-8599-4077713f96d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>OpenWindowNav('Preferences/Settings.aspx','RadWindowSettings'); return false;</value>
      <webElementGuid>75068d71-2d9a-44cc-8bfe-887af9e168c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_LinkButtonDistrictSettings</value>
      <webElementGuid>a13aeda5-365f-4f50-b159-9fd826ff6364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$LinkButtonDistrictSettings','')</value>
      <webElementGuid>89e78eba-e0f4-4000-bad2-2cdedaf3b241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>District Settings</value>
      <webElementGuid>bc72f60d-a0da-4cf9-867c-34b40659125b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_LinkButtonDistrictSettings&quot;)</value>
      <webElementGuid>2f5565b8-d84e-4ab3-9e98-0b79363e676c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_LinkButtonDistrictSettings']</value>
      <webElementGuid>c15c2f95-0757-462b-bff0-f8effa5b324b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ctl00_TableRowDistrictSettings']/td/a</value>
      <webElementGuid>35c03eaf-ed4b-481b-96c0-f8e13f09a854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'District Settings')]</value>
      <webElementGuid>3480deff-698b-4ec3-ac3a-1dd8c1580c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Department Settings'])[1]/following::a[1]</value>
      <webElementGuid>708853eb-a5ab-4ddd-90ac-e41e2dac877d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Charge Types'])[1]/following::a[2]</value>
      <webElementGuid>33b324e0-2d7f-4cef-b91a-6ddca5fd7441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-Mail Notifications'])[1]/preceding::a[1]</value>
      <webElementGuid>be95e770-df45-4a74-a1b1-2924d0111027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Funding Sources'])[1]/preceding::a[2]</value>
      <webElementGuid>0eaff3a7-3c2c-42f4-b54d-e49df7716c1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='District Settings']/parent::*</value>
      <webElementGuid>499c8ab7-644a-433d-8c1c-85c903d434c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$LinkButtonDistrictSettings','')&quot;)]</value>
      <webElementGuid>15074f56-ed17-46f9-af00-1786c510b510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/table/tbody/tr[4]/td/a</value>
      <webElementGuid>70f4ee30-8279-4805-9cee-8bc146f00779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_LinkButtonDistrictSettings' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$LinkButtonDistrictSettings&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'District Settings' or . = 'District Settings')]</value>
      <webElementGuid>2ef9c6e8-51c2-400e-bd02-c943f44e3f3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
