<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Staff dropdowns</name>
   <tag></tag>
   <elementGuidId>eca9b04f-8631-4990-8618-72f22980a614</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_RadPanelBar1_i1_staffDataPanelOptions</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_ContentPlaceHolder1_RadPanelBar1_i1_staffDataPanelOptions']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>023cc552-201e-4f12-b01b-ac93b08f1c81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_RadPanelBar1_i1_staffDataPanelOptions</value>
      <webElementGuid>23fda7d6-d662-4824-8532-ce4fa820c630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
						
                                    
                                        
                                            
                                                Product Type(s):  
                                            
                                            
                                                
							
								
									select
								
							Check All~`@#$%^&amp;*()_+{}|[]\:;',.?/SYPNO&lt;>S&lt;Y>1008PTY11105PTY11207PType12506PTy1ATHLETIC EQUIPMENT - NautilusATHLETIC EQUIPMENT - OTHERSATHLETIC EQUIPMENT - SCOREBOARDAUDIO/VISUAL EQUIPMENT - CAMERAAUDIO/VISUAL EQUIPMENT - CAMERA LENSAUDIO/VISUAL EQUIPMENT - DOCUMENT CAMERAAUDIO/VISUAL EQUIPMENT - FLAT SCREEN TVAUDIO/VISUAL EQUIPMENT - GAMING SYSTEMAUDIO/VISUAL EQUIPMENT - HEADPHONESAUDIO/VISUAL EQUIPMENT - INTERACTIVE WHITEBOARDAUDIO/VISUAL EQUIPMENT - OTHERSAUDIO/VISUAL EQUIPMENT - PROJECTORSAUDIO/VISUAL EQUIPMENT - SOUNDAUDIO/VISUAL EQUIPMENT - SPEAKERSAUDIO/VISUAL EQUIPMENT - TABLEAUDIO/VISUAL EQUIPMENT - TELESCOPE EQUIPMENTAUDIO/VISUAL EQUIPMENT - TELEVISIONAUDIO/VISUAL EQUIPMENT - TOUCH DISPLAYAUDIO/VISUAL EQUIPMENT - VIDEO PLAYERAUDIO/VISUAL EQUIPMENT- PROJECTOR SCREENAUTOMOTIVE REPAIR EQUIPMENTBOOKBUILDING - PORTABLE BUILDINGCALCULATORCART - CHARGINGCART - DCRCART - OTHERCATE EQUIPMENTCLASSROOM PERFORMANCE SYSTEMCOMMUNICATIONS SYSTEM - EMERGENCY SYSTEMCOMMUNICATIONS SYSTEM - OTHERSCOMMUNICATIONS SYSTEM - P A SYSTEMCOMMUNICATIONS SYSTEM - RADIOSCOMMUNICATIONS SYSTEM - SURVEILLANCE/ALARM SYSTEMCOMMUNICATIONS SYSTEM - TRANSMITTER/RECEIVER SYSComputer -AjiCOMPUTERS - ACCESSORYCOMPUTERS - AIOCOMPUTERS - CARTSCOMPUTERS - CPUCOMPUTERS - LAPTOPSCOMPUTERS - MONITORSCOMPUTERS - NETBOOKSCOMPUTERS - OTHERSCOMPUTERS - TABLETSDECORATIONSEMERGENCY EQUIPMENTFURNITUREHVAC - AIR CONDITIONINGHVAC - BOILERS &amp; STEAM SYSTEMHVAC - CENTRAL HEATING/AC SYSTEMHVAC - CHILLERSHVAC - COOLING TOWERSHVAC - GENERATORSHVAC - NETWORK CONTROL MODULEHVAC - OTHERSHVAC - ROOFTOP UNITSImPTy0605ImPTy0705ImPType0505KITCHEN EQUIPMENT - BEVERAGE COOLERKITCHEN EQUIPMENT - BRAISING PANKITCHEN EQUIPMENT - CASH REGISTERKITCHEN EQUIPMENT - COMMERCIAL WASHERKITCHEN EQUIPMENT - DISHWASHERKITCHEN EQUIPMENT - FOOD MIXERKITCHEN EQUIPMENT - FOOD WARMERKITCHEN EQUIPMENT - FREEZERKITCHEN EQUIPMENT - FREEZER/COOLERKITCHEN EQUIPMENT - GRILLKITCHEN EQUIPMENT - HOOD VENTKITCHEN EQUIPMENT - ICE MACHINEKITCHEN EQUIPMENT - KETTLEKITCHEN EQUIPMENT - MILK/ICE CREAM COOLERKITCHEN EQUIPMENT - MOBILE BUFFETKITCHEN EQUIPMENT - OTHERSKITCHEN EQUIPMENT - OVENKITCHEN EQUIPMENT - PIZZA OVEN/MAKERKITCHEN EQUIPMENT - RANGEKITCHEN EQUIPMENT - REFRIGERATORKITCHEN EQUIPMENT - SERVING LINE/COUNTERKITCHEN EQUIPMENT - SMOOTHIE MACHINEKITCHEN EQUIPMENT - STEAMERKITCHEN EQUIPMENT - VENDING MACHINEKITCHEN EQUIPMENT - WALK-IN FREEZERKITCHEN EQUIPMENT - WALK-IN REFRIGERATORKITCHEN EQUIPMENT - WASH BASIN SINKMAINT/GRNDS/CUSTD EQUIP-HIGH PRESSURE WASHERMAINT/GRNDS/CUSTD EQUIPMENT - CUSTODIALMAINT/GRNDS/CUSTD EQUIPMENT - OTHERSMAINT/GRNDS/CUSTD EQUIPMENT - TRACTORS/MOWERSMAINT/GRNDS/CUSTD EQUIPMENT- CARPET CLEANINGMAINT/GRNDS/CUSTD EQUIPMENT- HEAVY/CONSTRUCTION EQMEDICAL EQUIPMENTMEDICAL EQUIPMENT - AUDIOLOGICALMUSICAL - BrassMUSICAL - Misc StringsMUSICAL - OtherMUSICAL - PercussionMUSICAL INSTRUMENTSMUSICAL INSTRUMENTS - BASSMUSICAL INSTRUMENTS - BASSOONMUSICAL INSTRUMENTS - CelloMUSICAL INSTRUMENTS - MARIMBAMUSICAL INSTRUMENTS - OTHERSMUSICAL INSTRUMENTS - PIANOMUSICAL INSTRUMENTS - SAXOPHONEMUSICAL INSTRUMENTS - SOUSAPHONEMUSICAL INSTRUMENTS - TIMPANIMUSICAL INSTRUMENTS - TUBAMUSICAL INSTRUMENTS - VIOLAMUSICAL INSTRUMENTS - VIOLINMUSICAL INSTRUMENTS - WOODWINDNETWORK EQUIPMENT - ACCESS POINTNETWORK EQUIPMENT - BATTERY PACKNETWORK EQUIPMENT - OTHERSNETWORK EQUIPMENT - SERVERSNETWORK EQUIPMENT - SWITCHESOFFICE EQUIPMENT - OTHERSOFFICE EQUIPMENT - SHREDDEROTHER EQUIPMENT - CHILD CAREOTHER EQUIPMENT - CUTTING MACHINESOTHER EQUIPMENT - KILNOTHER EQUIPMENT - MISC FIXTURE EQUIPMENTP1PHONE - CELLULARPHONE - OFFICEPHOTOCOPIER - COPIERSPRINTERS - 3DPRINTERS - ALL-IN-ONEPRINTERS - FAX MACHINESPRINTERS - ID BADGEPRINTERS - LAMINATORSPRINTERS - LARGE FORMATPRINTERS - LASER PRINTERPRINTERS - MULTI FUNCTIONPRINTERS - OTHERSPRINTERS - SCANNERSPRINTING EQUIPMENT - COMMERCIAL PRINTING PRESSPType1PType1101PTypeLarge1234567891011121314151617181920212223242RECREATIONAL EQUIPMENT - PLAYGROUND EQUIPMENTSCIENCE/LABORATORY EQUIPMENTSPED EQUIPMENT - AUDIOSPED EQUIPMENT - SPECIAL NEEDSSPED EQUIPMENT - VISIONSTAGE &amp; AUDITORIUM EQUIPMENTSY_PNO&lt;>S&lt;Y>SY_WithACCSystem devicesTEACHING MATERIALSTEACHING MATERIALS - READ 180TEACHING MATERIALS - REAL BOOKSTEACHING MATERIALS - SYSTEM 44test protest_nikitatestingUPSVEHICLES - BUSESVEHICLES - OTHERSVEHICLES - SEDANSVEHICLES - TRAILERSVEHICLES - TRUCKSVEHICLES - VANSWAREHOUSE EQUIPMENT - LIFT JACKSWAREHOUSE EQUIPMENT - SHOP TOOLS/EQUIPMENTZCOMPUTERS - IPADSZPRINTERS - LAMINATORS
						
                                            
                                        
                                        
                                            
                                                Grade(s):
                                            
                                            
                                                
							
								
									select
								
							Check All--1-2-30010211011121A1A / 2A1A BIL1B1B   2WAY1C1C    Bilingual1C/KC1D1D BILINGUAL1E1F1G1st1st Grade22A2A / 1A2B2B BIL2C2C / 3C2C Bilingual2C/3C2D2D  BILINGUAL2D/1C2E2F2G2nd2nd Grade33A3A / 2B3B3C3C  BILINGUAL3C/4D GEN3D3D  BILINGUAL3D/4C GEN-M/SCI3D/4C GEN-RLA/SS3E3F3G3rd3rd Grade44A4B4B/5C4C4C  BILINGUAL4C / 5C4D4D  BILINGUAL4E4E/5E4F4G4th4th/5th4th/5th Grade55A5A BIL5B5B BIL5C5C  BILINGUAL5C / 4C5C GEN5D5D  BILINGUAL5E5F5th66A6B6D7733G Copy Center/Graphics NCX 1st FL733G Graphics733G Graphics @ 9400 NCX733G Graphics @9400 NCX Copy Center  1st FL899 10 11 129-12ArtAssistant PrincipalAsst PrinAutism Unit 3-5Autism Unit K-2B-TechB-Tech Office ClerkBandBilingualBilingual 1stCafeteriaCafeteria LeadCATECICClerkCollegeCommunity LiaisonCounselorCRCCustodialCustodianCustodian (Lead)Custodian LeadDanceDyslexiaECELAR COACHElectivesELPK4B1ELPK4B1 TAELPK4B2ELPK4B2 BILELPK4B2 TAELPK4G3ELPK4G3 TAEnglishEnglish IVFine ArtsFloatingFLSGYMHall MonitorHealthHS PrincipalInclusionInstructional CoachInstructional Coach - ELARInstructional Coach - MathISSKK/1KAKBKB  BilingualKB / 1AKB / 1BKB/1B BILKCKC   2 WAYKC/1CKDKEKE / 1EKFKGkinderKinder Bilingual -KBKinder CollabKindergartenKNLCCLibrarianLOTEMathMath CoachMedia SpecialistMonitorMusicN/N/ANULLNurseOffice ManagerOrchestraParent LiasionParking Lot AttnPE CoachPhysical EducationPKPK - GEN EDPK APK CPK-5PK-APK-BPK-CPK-DPK1BPK1B TAPK2APK2BPK2B TAPK3PK3B TAPK3EPK3GPK3Y1B 3Y2BPK3Y1B 3Y2B TAPk4 TAPK4GPKAPL CoordinatorPLLPPCDPPCD TAPRE-K  (BIL) 2WAYPRE-K  BILINGUALPreKPreK CollabPreK-3Prek-4PrincipalReading CoachreceivingReconnectionRegistrarResourceScienceSEASEBSECSecuritySocial StudiesSpecial EducationSPEDSPED TASpeechSTEM Coor.Summer SchoolTAGTCATCBTCCTeacher AssistantTech ApplicationsTechnologyTesting Coordinator
						
                                            
                                        
                                        
                                            
                                                Transfer tags when in the status of:
                                            
                                            
                                                
							
								
									select
								
							Check AllAuctionedDisposedIn RepairIn UseLostPending LostPending StolenRecycledReturned to VendorSoldStolenSurplusUsed For Parts
						
                                            
                                        
                                    
                                
					</value>
      <webElementGuid>95b0e952-a17f-405d-bace-0bf2680f4a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_RadPanelBar1_i1_staffDataPanelOptions&quot;)</value>
      <webElementGuid>a27286f3-4a88-4c3c-9902-6ad2f31d598c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIPWebIT/Staff Xfer Check/iframe_Close_RadWindowSettings</value>
      <webElementGuid>89e7015a-7d27-4df4-a0e7-016654887365</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder1_RadPanelBar1_i1_staffDataPanelOptions']</value>
      <webElementGuid>893c34eb-3cd0-4a37-a5c8-b0e74c4d52c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder1_RadPanelBar1_i1_staffDataPanel']/div</value>
      <webElementGuid>c1194ea2-c4d3-4a09-9fef-b85b2b2a6b30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automatically Transfer Staff Inventory Data'])[1]/following::div[1]</value>
      <webElementGuid>e51a6e57-70bc-49ae-8b7e-5f6710ea3abb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automatically Transfer Student Inventory Data'])[1]/following::div[2]</value>
      <webElementGuid>fef5b497-d7da-44ad-953e-47ccca5dab5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>e6d526c1-d041-4997-8c02-6aa38f47e618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ctl00_ContentPlaceHolder1_RadPanelBar1_i1_staffDataPanelOptions' and (text() = concat(&quot;
						
                                    
                                        
                                            
                                                Product Type(s):  
                                            
                                            
                                                
							
								
									select
								
							Check All~`@#$%^&amp;*()_+{}|[]\:;&quot; , &quot;'&quot; , &quot;,.?/SYPNO&lt;>S&lt;Y>1008PTY11105PTY11207PType12506PTy1ATHLETIC EQUIPMENT - NautilusATHLETIC EQUIPMENT - OTHERSATHLETIC EQUIPMENT - SCOREBOARDAUDIO/VISUAL EQUIPMENT - CAMERAAUDIO/VISUAL EQUIPMENT - CAMERA LENSAUDIO/VISUAL EQUIPMENT - DOCUMENT CAMERAAUDIO/VISUAL EQUIPMENT - FLAT SCREEN TVAUDIO/VISUAL EQUIPMENT - GAMING SYSTEMAUDIO/VISUAL EQUIPMENT - HEADPHONESAUDIO/VISUAL EQUIPMENT - INTERACTIVE WHITEBOARDAUDIO/VISUAL EQUIPMENT - OTHERSAUDIO/VISUAL EQUIPMENT - PROJECTORSAUDIO/VISUAL EQUIPMENT - SOUNDAUDIO/VISUAL EQUIPMENT - SPEAKERSAUDIO/VISUAL EQUIPMENT - TABLEAUDIO/VISUAL EQUIPMENT - TELESCOPE EQUIPMENTAUDIO/VISUAL EQUIPMENT - TELEVISIONAUDIO/VISUAL EQUIPMENT - TOUCH DISPLAYAUDIO/VISUAL EQUIPMENT - VIDEO PLAYERAUDIO/VISUAL EQUIPMENT- PROJECTOR SCREENAUTOMOTIVE REPAIR EQUIPMENTBOOKBUILDING - PORTABLE BUILDINGCALCULATORCART - CHARGINGCART - DCRCART - OTHERCATE EQUIPMENTCLASSROOM PERFORMANCE SYSTEMCOMMUNICATIONS SYSTEM - EMERGENCY SYSTEMCOMMUNICATIONS SYSTEM - OTHERSCOMMUNICATIONS SYSTEM - P A SYSTEMCOMMUNICATIONS SYSTEM - RADIOSCOMMUNICATIONS SYSTEM - SURVEILLANCE/ALARM SYSTEMCOMMUNICATIONS SYSTEM - TRANSMITTER/RECEIVER SYSComputer -AjiCOMPUTERS - ACCESSORYCOMPUTERS - AIOCOMPUTERS - CARTSCOMPUTERS - CPUCOMPUTERS - LAPTOPSCOMPUTERS - MONITORSCOMPUTERS - NETBOOKSCOMPUTERS - OTHERSCOMPUTERS - TABLETSDECORATIONSEMERGENCY EQUIPMENTFURNITUREHVAC - AIR CONDITIONINGHVAC - BOILERS &amp; STEAM SYSTEMHVAC - CENTRAL HEATING/AC SYSTEMHVAC - CHILLERSHVAC - COOLING TOWERSHVAC - GENERATORSHVAC - NETWORK CONTROL MODULEHVAC - OTHERSHVAC - ROOFTOP UNITSImPTy0605ImPTy0705ImPType0505KITCHEN EQUIPMENT - BEVERAGE COOLERKITCHEN EQUIPMENT - BRAISING PANKITCHEN EQUIPMENT - CASH REGISTERKITCHEN EQUIPMENT - COMMERCIAL WASHERKITCHEN EQUIPMENT - DISHWASHERKITCHEN EQUIPMENT - FOOD MIXERKITCHEN EQUIPMENT - FOOD WARMERKITCHEN EQUIPMENT - FREEZERKITCHEN EQUIPMENT - FREEZER/COOLERKITCHEN EQUIPMENT - GRILLKITCHEN EQUIPMENT - HOOD VENTKITCHEN EQUIPMENT - ICE MACHINEKITCHEN EQUIPMENT - KETTLEKITCHEN EQUIPMENT - MILK/ICE CREAM COOLERKITCHEN EQUIPMENT - MOBILE BUFFETKITCHEN EQUIPMENT - OTHERSKITCHEN EQUIPMENT - OVENKITCHEN EQUIPMENT - PIZZA OVEN/MAKERKITCHEN EQUIPMENT - RANGEKITCHEN EQUIPMENT - REFRIGERATORKITCHEN EQUIPMENT - SERVING LINE/COUNTERKITCHEN EQUIPMENT - SMOOTHIE MACHINEKITCHEN EQUIPMENT - STEAMERKITCHEN EQUIPMENT - VENDING MACHINEKITCHEN EQUIPMENT - WALK-IN FREEZERKITCHEN EQUIPMENT - WALK-IN REFRIGERATORKITCHEN EQUIPMENT - WASH BASIN SINKMAINT/GRNDS/CUSTD EQUIP-HIGH PRESSURE WASHERMAINT/GRNDS/CUSTD EQUIPMENT - CUSTODIALMAINT/GRNDS/CUSTD EQUIPMENT - OTHERSMAINT/GRNDS/CUSTD EQUIPMENT - TRACTORS/MOWERSMAINT/GRNDS/CUSTD EQUIPMENT- CARPET CLEANINGMAINT/GRNDS/CUSTD EQUIPMENT- HEAVY/CONSTRUCTION EQMEDICAL EQUIPMENTMEDICAL EQUIPMENT - AUDIOLOGICALMUSICAL - BrassMUSICAL - Misc StringsMUSICAL - OtherMUSICAL - PercussionMUSICAL INSTRUMENTSMUSICAL INSTRUMENTS - BASSMUSICAL INSTRUMENTS - BASSOONMUSICAL INSTRUMENTS - CelloMUSICAL INSTRUMENTS - MARIMBAMUSICAL INSTRUMENTS - OTHERSMUSICAL INSTRUMENTS - PIANOMUSICAL INSTRUMENTS - SAXOPHONEMUSICAL INSTRUMENTS - SOUSAPHONEMUSICAL INSTRUMENTS - TIMPANIMUSICAL INSTRUMENTS - TUBAMUSICAL INSTRUMENTS - VIOLAMUSICAL INSTRUMENTS - VIOLINMUSICAL INSTRUMENTS - WOODWINDNETWORK EQUIPMENT - ACCESS POINTNETWORK EQUIPMENT - BATTERY PACKNETWORK EQUIPMENT - OTHERSNETWORK EQUIPMENT - SERVERSNETWORK EQUIPMENT - SWITCHESOFFICE EQUIPMENT - OTHERSOFFICE EQUIPMENT - SHREDDEROTHER EQUIPMENT - CHILD CAREOTHER EQUIPMENT - CUTTING MACHINESOTHER EQUIPMENT - KILNOTHER EQUIPMENT - MISC FIXTURE EQUIPMENTP1PHONE - CELLULARPHONE - OFFICEPHOTOCOPIER - COPIERSPRINTERS - 3DPRINTERS - ALL-IN-ONEPRINTERS - FAX MACHINESPRINTERS - ID BADGEPRINTERS - LAMINATORSPRINTERS - LARGE FORMATPRINTERS - LASER PRINTERPRINTERS - MULTI FUNCTIONPRINTERS - OTHERSPRINTERS - SCANNERSPRINTING EQUIPMENT - COMMERCIAL PRINTING PRESSPType1PType1101PTypeLarge1234567891011121314151617181920212223242RECREATIONAL EQUIPMENT - PLAYGROUND EQUIPMENTSCIENCE/LABORATORY EQUIPMENTSPED EQUIPMENT - AUDIOSPED EQUIPMENT - SPECIAL NEEDSSPED EQUIPMENT - VISIONSTAGE &amp; AUDITORIUM EQUIPMENTSY_PNO&lt;>S&lt;Y>SY_WithACCSystem devicesTEACHING MATERIALSTEACHING MATERIALS - READ 180TEACHING MATERIALS - REAL BOOKSTEACHING MATERIALS - SYSTEM 44test protest_nikitatestingUPSVEHICLES - BUSESVEHICLES - OTHERSVEHICLES - SEDANSVEHICLES - TRAILERSVEHICLES - TRUCKSVEHICLES - VANSWAREHOUSE EQUIPMENT - LIFT JACKSWAREHOUSE EQUIPMENT - SHOP TOOLS/EQUIPMENTZCOMPUTERS - IPADSZPRINTERS - LAMINATORS
						
                                            
                                        
                                        
                                            
                                                Grade(s):
                                            
                                            
                                                
							
								
									select
								
							Check All--1-2-30010211011121A1A / 2A1A BIL1B1B   2WAY1C1C    Bilingual1C/KC1D1D BILINGUAL1E1F1G1st1st Grade22A2A / 1A2B2B BIL2C2C / 3C2C Bilingual2C/3C2D2D  BILINGUAL2D/1C2E2F2G2nd2nd Grade33A3A / 2B3B3C3C  BILINGUAL3C/4D GEN3D3D  BILINGUAL3D/4C GEN-M/SCI3D/4C GEN-RLA/SS3E3F3G3rd3rd Grade44A4B4B/5C4C4C  BILINGUAL4C / 5C4D4D  BILINGUAL4E4E/5E4F4G4th4th/5th4th/5th Grade55A5A BIL5B5B BIL5C5C  BILINGUAL5C / 4C5C GEN5D5D  BILINGUAL5E5F5th66A6B6D7733G Copy Center/Graphics NCX 1st FL733G Graphics733G Graphics @ 9400 NCX733G Graphics @9400 NCX Copy Center  1st FL899 10 11 129-12ArtAssistant PrincipalAsst PrinAutism Unit 3-5Autism Unit K-2B-TechB-Tech Office ClerkBandBilingualBilingual 1stCafeteriaCafeteria LeadCATECICClerkCollegeCommunity LiaisonCounselorCRCCustodialCustodianCustodian (Lead)Custodian LeadDanceDyslexiaECELAR COACHElectivesELPK4B1ELPK4B1 TAELPK4B2ELPK4B2 BILELPK4B2 TAELPK4G3ELPK4G3 TAEnglishEnglish IVFine ArtsFloatingFLSGYMHall MonitorHealthHS PrincipalInclusionInstructional CoachInstructional Coach - ELARInstructional Coach - MathISSKK/1KAKBKB  BilingualKB / 1AKB / 1BKB/1B BILKCKC   2 WAYKC/1CKDKEKE / 1EKFKGkinderKinder Bilingual -KBKinder CollabKindergartenKNLCCLibrarianLOTEMathMath CoachMedia SpecialistMonitorMusicN/N/ANULLNurseOffice ManagerOrchestraParent LiasionParking Lot AttnPE CoachPhysical EducationPKPK - GEN EDPK APK CPK-5PK-APK-BPK-CPK-DPK1BPK1B TAPK2APK2BPK2B TAPK3PK3B TAPK3EPK3GPK3Y1B 3Y2BPK3Y1B 3Y2B TAPk4 TAPK4GPKAPL CoordinatorPLLPPCDPPCD TAPRE-K  (BIL) 2WAYPRE-K  BILINGUALPreKPreK CollabPreK-3Prek-4PrincipalReading CoachreceivingReconnectionRegistrarResourceScienceSEASEBSECSecuritySocial StudiesSpecial EducationSPEDSPED TASpeechSTEM Coor.Summer SchoolTAGTCATCBTCCTeacher AssistantTech ApplicationsTechnologyTesting Coordinator
						
                                            
                                        
                                        
                                            
                                                Transfer tags when in the status of:
                                            
                                            
                                                
							
								
									select
								
							Check AllAuctionedDisposedIn RepairIn UseLostPending LostPending StolenRecycledReturned to VendorSoldStolenSurplusUsed For Parts
						
                                            
                                        
                                    
                                
					&quot;) or . = concat(&quot;
						
                                    
                                        
                                            
                                                Product Type(s):  
                                            
                                            
                                                
							
								
									select
								
							Check All~`@#$%^&amp;*()_+{}|[]\:;&quot; , &quot;'&quot; , &quot;,.?/SYPNO&lt;>S&lt;Y>1008PTY11105PTY11207PType12506PTy1ATHLETIC EQUIPMENT - NautilusATHLETIC EQUIPMENT - OTHERSATHLETIC EQUIPMENT - SCOREBOARDAUDIO/VISUAL EQUIPMENT - CAMERAAUDIO/VISUAL EQUIPMENT - CAMERA LENSAUDIO/VISUAL EQUIPMENT - DOCUMENT CAMERAAUDIO/VISUAL EQUIPMENT - FLAT SCREEN TVAUDIO/VISUAL EQUIPMENT - GAMING SYSTEMAUDIO/VISUAL EQUIPMENT - HEADPHONESAUDIO/VISUAL EQUIPMENT - INTERACTIVE WHITEBOARDAUDIO/VISUAL EQUIPMENT - OTHERSAUDIO/VISUAL EQUIPMENT - PROJECTORSAUDIO/VISUAL EQUIPMENT - SOUNDAUDIO/VISUAL EQUIPMENT - SPEAKERSAUDIO/VISUAL EQUIPMENT - TABLEAUDIO/VISUAL EQUIPMENT - TELESCOPE EQUIPMENTAUDIO/VISUAL EQUIPMENT - TELEVISIONAUDIO/VISUAL EQUIPMENT - TOUCH DISPLAYAUDIO/VISUAL EQUIPMENT - VIDEO PLAYERAUDIO/VISUAL EQUIPMENT- PROJECTOR SCREENAUTOMOTIVE REPAIR EQUIPMENTBOOKBUILDING - PORTABLE BUILDINGCALCULATORCART - CHARGINGCART - DCRCART - OTHERCATE EQUIPMENTCLASSROOM PERFORMANCE SYSTEMCOMMUNICATIONS SYSTEM - EMERGENCY SYSTEMCOMMUNICATIONS SYSTEM - OTHERSCOMMUNICATIONS SYSTEM - P A SYSTEMCOMMUNICATIONS SYSTEM - RADIOSCOMMUNICATIONS SYSTEM - SURVEILLANCE/ALARM SYSTEMCOMMUNICATIONS SYSTEM - TRANSMITTER/RECEIVER SYSComputer -AjiCOMPUTERS - ACCESSORYCOMPUTERS - AIOCOMPUTERS - CARTSCOMPUTERS - CPUCOMPUTERS - LAPTOPSCOMPUTERS - MONITORSCOMPUTERS - NETBOOKSCOMPUTERS - OTHERSCOMPUTERS - TABLETSDECORATIONSEMERGENCY EQUIPMENTFURNITUREHVAC - AIR CONDITIONINGHVAC - BOILERS &amp; STEAM SYSTEMHVAC - CENTRAL HEATING/AC SYSTEMHVAC - CHILLERSHVAC - COOLING TOWERSHVAC - GENERATORSHVAC - NETWORK CONTROL MODULEHVAC - OTHERSHVAC - ROOFTOP UNITSImPTy0605ImPTy0705ImPType0505KITCHEN EQUIPMENT - BEVERAGE COOLERKITCHEN EQUIPMENT - BRAISING PANKITCHEN EQUIPMENT - CASH REGISTERKITCHEN EQUIPMENT - COMMERCIAL WASHERKITCHEN EQUIPMENT - DISHWASHERKITCHEN EQUIPMENT - FOOD MIXERKITCHEN EQUIPMENT - FOOD WARMERKITCHEN EQUIPMENT - FREEZERKITCHEN EQUIPMENT - FREEZER/COOLERKITCHEN EQUIPMENT - GRILLKITCHEN EQUIPMENT - HOOD VENTKITCHEN EQUIPMENT - ICE MACHINEKITCHEN EQUIPMENT - KETTLEKITCHEN EQUIPMENT - MILK/ICE CREAM COOLERKITCHEN EQUIPMENT - MOBILE BUFFETKITCHEN EQUIPMENT - OTHERSKITCHEN EQUIPMENT - OVENKITCHEN EQUIPMENT - PIZZA OVEN/MAKERKITCHEN EQUIPMENT - RANGEKITCHEN EQUIPMENT - REFRIGERATORKITCHEN EQUIPMENT - SERVING LINE/COUNTERKITCHEN EQUIPMENT - SMOOTHIE MACHINEKITCHEN EQUIPMENT - STEAMERKITCHEN EQUIPMENT - VENDING MACHINEKITCHEN EQUIPMENT - WALK-IN FREEZERKITCHEN EQUIPMENT - WALK-IN REFRIGERATORKITCHEN EQUIPMENT - WASH BASIN SINKMAINT/GRNDS/CUSTD EQUIP-HIGH PRESSURE WASHERMAINT/GRNDS/CUSTD EQUIPMENT - CUSTODIALMAINT/GRNDS/CUSTD EQUIPMENT - OTHERSMAINT/GRNDS/CUSTD EQUIPMENT - TRACTORS/MOWERSMAINT/GRNDS/CUSTD EQUIPMENT- CARPET CLEANINGMAINT/GRNDS/CUSTD EQUIPMENT- HEAVY/CONSTRUCTION EQMEDICAL EQUIPMENTMEDICAL EQUIPMENT - AUDIOLOGICALMUSICAL - BrassMUSICAL - Misc StringsMUSICAL - OtherMUSICAL - PercussionMUSICAL INSTRUMENTSMUSICAL INSTRUMENTS - BASSMUSICAL INSTRUMENTS - BASSOONMUSICAL INSTRUMENTS - CelloMUSICAL INSTRUMENTS - MARIMBAMUSICAL INSTRUMENTS - OTHERSMUSICAL INSTRUMENTS - PIANOMUSICAL INSTRUMENTS - SAXOPHONEMUSICAL INSTRUMENTS - SOUSAPHONEMUSICAL INSTRUMENTS - TIMPANIMUSICAL INSTRUMENTS - TUBAMUSICAL INSTRUMENTS - VIOLAMUSICAL INSTRUMENTS - VIOLINMUSICAL INSTRUMENTS - WOODWINDNETWORK EQUIPMENT - ACCESS POINTNETWORK EQUIPMENT - BATTERY PACKNETWORK EQUIPMENT - OTHERSNETWORK EQUIPMENT - SERVERSNETWORK EQUIPMENT - SWITCHESOFFICE EQUIPMENT - OTHERSOFFICE EQUIPMENT - SHREDDEROTHER EQUIPMENT - CHILD CAREOTHER EQUIPMENT - CUTTING MACHINESOTHER EQUIPMENT - KILNOTHER EQUIPMENT - MISC FIXTURE EQUIPMENTP1PHONE - CELLULARPHONE - OFFICEPHOTOCOPIER - COPIERSPRINTERS - 3DPRINTERS - ALL-IN-ONEPRINTERS - FAX MACHINESPRINTERS - ID BADGEPRINTERS - LAMINATORSPRINTERS - LARGE FORMATPRINTERS - LASER PRINTERPRINTERS - MULTI FUNCTIONPRINTERS - OTHERSPRINTERS - SCANNERSPRINTING EQUIPMENT - COMMERCIAL PRINTING PRESSPType1PType1101PTypeLarge1234567891011121314151617181920212223242RECREATIONAL EQUIPMENT - PLAYGROUND EQUIPMENTSCIENCE/LABORATORY EQUIPMENTSPED EQUIPMENT - AUDIOSPED EQUIPMENT - SPECIAL NEEDSSPED EQUIPMENT - VISIONSTAGE &amp; AUDITORIUM EQUIPMENTSY_PNO&lt;>S&lt;Y>SY_WithACCSystem devicesTEACHING MATERIALSTEACHING MATERIALS - READ 180TEACHING MATERIALS - REAL BOOKSTEACHING MATERIALS - SYSTEM 44test protest_nikitatestingUPSVEHICLES - BUSESVEHICLES - OTHERSVEHICLES - SEDANSVEHICLES - TRAILERSVEHICLES - TRUCKSVEHICLES - VANSWAREHOUSE EQUIPMENT - LIFT JACKSWAREHOUSE EQUIPMENT - SHOP TOOLS/EQUIPMENTZCOMPUTERS - IPADSZPRINTERS - LAMINATORS
						
                                            
                                        
                                        
                                            
                                                Grade(s):
                                            
                                            
                                                
							
								
									select
								
							Check All--1-2-30010211011121A1A / 2A1A BIL1B1B   2WAY1C1C    Bilingual1C/KC1D1D BILINGUAL1E1F1G1st1st Grade22A2A / 1A2B2B BIL2C2C / 3C2C Bilingual2C/3C2D2D  BILINGUAL2D/1C2E2F2G2nd2nd Grade33A3A / 2B3B3C3C  BILINGUAL3C/4D GEN3D3D  BILINGUAL3D/4C GEN-M/SCI3D/4C GEN-RLA/SS3E3F3G3rd3rd Grade44A4B4B/5C4C4C  BILINGUAL4C / 5C4D4D  BILINGUAL4E4E/5E4F4G4th4th/5th4th/5th Grade55A5A BIL5B5B BIL5C5C  BILINGUAL5C / 4C5C GEN5D5D  BILINGUAL5E5F5th66A6B6D7733G Copy Center/Graphics NCX 1st FL733G Graphics733G Graphics @ 9400 NCX733G Graphics @9400 NCX Copy Center  1st FL899 10 11 129-12ArtAssistant PrincipalAsst PrinAutism Unit 3-5Autism Unit K-2B-TechB-Tech Office ClerkBandBilingualBilingual 1stCafeteriaCafeteria LeadCATECICClerkCollegeCommunity LiaisonCounselorCRCCustodialCustodianCustodian (Lead)Custodian LeadDanceDyslexiaECELAR COACHElectivesELPK4B1ELPK4B1 TAELPK4B2ELPK4B2 BILELPK4B2 TAELPK4G3ELPK4G3 TAEnglishEnglish IVFine ArtsFloatingFLSGYMHall MonitorHealthHS PrincipalInclusionInstructional CoachInstructional Coach - ELARInstructional Coach - MathISSKK/1KAKBKB  BilingualKB / 1AKB / 1BKB/1B BILKCKC   2 WAYKC/1CKDKEKE / 1EKFKGkinderKinder Bilingual -KBKinder CollabKindergartenKNLCCLibrarianLOTEMathMath CoachMedia SpecialistMonitorMusicN/N/ANULLNurseOffice ManagerOrchestraParent LiasionParking Lot AttnPE CoachPhysical EducationPKPK - GEN EDPK APK CPK-5PK-APK-BPK-CPK-DPK1BPK1B TAPK2APK2BPK2B TAPK3PK3B TAPK3EPK3GPK3Y1B 3Y2BPK3Y1B 3Y2B TAPk4 TAPK4GPKAPL CoordinatorPLLPPCDPPCD TAPRE-K  (BIL) 2WAYPRE-K  BILINGUALPreKPreK CollabPreK-3Prek-4PrincipalReading CoachreceivingReconnectionRegistrarResourceScienceSEASEBSECSecuritySocial StudiesSpecial EducationSPEDSPED TASpeechSTEM Coor.Summer SchoolTAGTCATCBTCCTeacher AssistantTech ApplicationsTechnologyTesting Coordinator
						
                                            
                                        
                                        
                                            
                                                Transfer tags when in the status of:
                                            
                                            
                                                
							
								
									select
								
							Check AllAuctionedDisposedIn RepairIn UseLostPending LostPending StolenRecycledReturned to VendorSoldStolenSurplusUsed For Parts
						
                                            
                                        
                                    
                                
					&quot;))]</value>
      <webElementGuid>1cfb901c-84fc-4f74-b583-4e4fa3838fd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
