<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Automatically Transfer Staff Inventory Data</name>
   <tag></tag>
   <elementGuidId>982e97db-a68f-461a-bb50-ee66037cea9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_RadPanelBar1_i1_staffDataPanel > span.BlueText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_ContentPlaceHolder1_RadPanelBar1_i1_staffDataPanel']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5e03719f-bf22-4fba-9d64-aa2ae8fa5a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>BlueText</value>
      <webElementGuid>c185d7b3-9813-45a3-87e8-abe8ebcfb3ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Automatically Transfer Staff Inventory Data</value>
      <webElementGuid>5af19d82-a866-4ddd-b7d6-fff7247b7c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_RadPanelBar1_i1_staffDataPanel&quot;)/span[@class=&quot;BlueText&quot;]</value>
      <webElementGuid>8404a803-d989-4845-8759-690dd77f7bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIPWebIT/Staff Xfer Check/iframe_Close_RadWindowSettings</value>
      <webElementGuid>0c832ffd-81e4-4d4c-a8ff-ec620e6eadff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder1_RadPanelBar1_i1_staffDataPanel']/span[2]</value>
      <webElementGuid>4ffecab6-63a0-454d-b4f4-b6137423e3ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automatically Transfer Student Inventory Data'])[1]/following::span[2]</value>
      <webElementGuid>5d835555-f5eb-4ead-8100-741fbe57d38e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Staff/Student Inventory Data'])[1]/following::span[4]</value>
      <webElementGuid>28367de5-0f19-4581-8a5e-c80320976580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='select'])[2]/preceding::span[2]</value>
      <webElementGuid>d3e88637-f992-4659-bcaf-6041bca5d71a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Automatically Transfer Staff Inventory Data']/parent::*</value>
      <webElementGuid>9ec63197-0d1f-4d2a-a747-81523bf85e9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span[2]</value>
      <webElementGuid>b5453689-60c1-4fd4-9d56-bfd1a5735e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Automatically Transfer Staff Inventory Data' or . = 'Automatically Transfer Staff Inventory Data')]</value>
      <webElementGuid>0a8828c6-50a2-491e-8b6d-6626b2cb7486</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
