<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Version</name>
   <tag></tag>
   <elementGuidId>63ac3f36-1071-4102-a599-28f1778f54db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='body']/section/div/hgroup[2]/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>cdb42e05-d66d-4963-b8cd-061a3baae134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Version:  2.1.0.0</value>
      <webElementGuid>582c7828-396a-4bb9-a81a-012c35100c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/section[@class=&quot;featured&quot;]/div[@class=&quot;content-wrapper&quot;]/hgroup[@class=&quot;version&quot;]/h2[1]</value>
      <webElementGuid>b4cc1956-9b1d-489f-a755-469b1d6b61f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='body']/section/div/hgroup[2]/h2</value>
      <webElementGuid>c992557c-0e8a-42ad-a57a-987e2d61c55a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asset Management Mobile Login.'])[1]/following::h2[1]</value>
      <webElementGuid>d2e5187d-be2f-4049-bf3a-044c14e4bb2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::h2[1]</value>
      <webElementGuid>86d46178-1e44-41e9-82d2-fd8c1add2bce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::h2[1]</value>
      <webElementGuid>595be933-54a4-42d7-a4e9-2cf4c68f467c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>2af2ba72-6085-4678-9c3e-0853e6770f1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Version:  2.1.0.0' or . = 'Version:  2.1.0.0')]</value>
      <webElementGuid>b9d13f79-2a12-46d1-84e9-8cc2d616d67d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
