<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Bank1A</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>2</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>be445957-587e-4359-b1ba-9fd47defdb89</testSuiteGuid>
   <testCaseLink>
      <guid>13c19749-402c-4efa-964e-b2bc9d4105d9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Post-Release/Generic Logins/Generic Retry</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>23b6f659-5b00-46a8-8a40-d00c99992a5a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Non-SSO/Bank1 A</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>23b6f659-5b00-46a8-8a40-d00c99992a5a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>url</value>
         <variableId>93e8f0f8-445b-4a18-baa3-f1a9660aee8f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>23b6f659-5b00-46a8-8a40-d00c99992a5a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>bbd1f073-e642-41e0-a0df-a5c41aa3c2f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>23b6f659-5b00-46a8-8a40-d00c99992a5a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>c9cb5c21-fedc-4225-b7b2-30cbddef2728</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
