<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Bank4B</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>2</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>31854666-6ad6-42b8-a7c4-a95677e3df83</testSuiteGuid>
   <testCaseLink>
      <guid>88e3d0d2-264d-44a2-bc75-b61f9de33c48</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Post-Release/Generic Logins/Generic Retry</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>da56014c-0029-4f9e-a22d-a55615fe9e9d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Non-SSO/Bank4 B</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>da56014c-0029-4f9e-a22d-a55615fe9e9d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>url</value>
         <variableId>93e8f0f8-445b-4a18-baa3-f1a9660aee8f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>da56014c-0029-4f9e-a22d-a55615fe9e9d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>bbd1f073-e642-41e0-a0df-a5c41aa3c2f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>da56014c-0029-4f9e-a22d-a55615fe9e9d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>c9cb5c21-fedc-4225-b7b2-30cbddef2728</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
