<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Bypass</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>2</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>d505f936-1836-4544-9f04-dd9542c121ea</testSuiteGuid>
   <testCaseLink>
      <guid>ca6b033f-9235-4d14-bfe8-6702a1dde931</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Post-Release/Generic Logins/Generic Retry</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>9538d150-1f07-48c0-b5b4-46be89cfdec1</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Non-SSO/Bypass</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>9538d150-1f07-48c0-b5b4-46be89cfdec1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>url</value>
         <variableId>93e8f0f8-445b-4a18-baa3-f1a9660aee8f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9538d150-1f07-48c0-b5b4-46be89cfdec1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>bbd1f073-e642-41e0-a0df-a5c41aa3c2f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9538d150-1f07-48c0-b5b4-46be89cfdec1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>c9cb5c21-fedc-4225-b7b2-30cbddef2728</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
