<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Demo_Training</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>2</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>0c40e908-ea37-41b7-8cfb-de4c887574ea</testSuiteGuid>
   <testCaseLink>
      <guid>f2974ea1-c77e-4c1b-81b8-2e1cf11e3c75</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Post-Release/Generic Logins/Generic Retry</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>65931d24-aaad-4c87-a7c1-71c9cdf08902</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Non-SSO/Demo_Train</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>65931d24-aaad-4c87-a7c1-71c9cdf08902</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>url</value>
         <variableId>93e8f0f8-445b-4a18-baa3-f1a9660aee8f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>65931d24-aaad-4c87-a7c1-71c9cdf08902</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>bbd1f073-e642-41e0-a0df-a5c41aa3c2f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>65931d24-aaad-4c87-a7c1-71c9cdf08902</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>c9cb5c21-fedc-4225-b7b2-30cbddef2728</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
