<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Quick Collect_RadWindowQuickCollect</name>
   <tag></tag>
   <elementGuidId>3b6c4c9a-b2af-446d-b494-a663c2d0026b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;RadWindowQuickCollect&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='RadWindowQuickCollect']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>7d440312-7271-4322-887c-340372e90ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RadWindowQuickCollect</value>
      <webElementGuid>1cf25c52-d2b5-4a42-9375-ad6ceb2c972c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/TIPWebIT/InventoryManagement/QuickCollect.aspx?Tag=157099&amp;Type=3&amp;rwndrnd=0.27563513242755633</value>
      <webElementGuid>ebfb9564-40cb-4b11-9c49-ede4606e1b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d9d32d5e-fbd6-454e-b85d-ecf8ba7789a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RadWindowWrapper_ctl00_RadWindowQuickCollect&quot;)/table[@class=&quot;rwTable&quot;]/tbody[1]/tr[@class=&quot;rwContentRow&quot;]/td[@class=&quot;rwWindowContent rwExternalContent&quot;]/iframe[1]</value>
      <webElementGuid>e6637892-3ea0-4b79-bac1-ea6051b02da7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='RadWindowQuickCollect']</value>
      <webElementGuid>8c5c39aa-239c-4ea5-aeb9-a680d5535bb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RadWindowWrapper_ctl00_RadWindowQuickCollect']/table/tbody/tr[2]/td[2]/iframe</value>
      <webElementGuid>1c692b5a-158c-4481-8fdd-c605a74d54a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>75b5d413-e7fe-4b52-9755-1633d76b7984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'RadWindowQuickCollect' and @src = '/TIPWebIT/InventoryManagement/QuickCollect.aspx?Tag=157099&amp;Type=3&amp;rwndrnd=0.27563513242755633']</value>
      <webElementGuid>653123d4-3c40-4d76-a2d7-bcc9712ad8e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
