<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Save</name>
   <tag></tag>
   <elementGuidId>b4734d5b-6e40-449a-a07a-2c496309a95c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_TagNumberSaveImageButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder1_TagNumberSaveImageButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce462302-1396-4c60-9770-6cdb0ac654a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>0b3a0cd3-07cc-478c-a96d-2fc45c14f762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$TagNumberSaveImageButton</value>
      <webElementGuid>ce1e97b4-1a85-4ffb-9426-c5d740d43ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_TagNumberSaveImageButton</value>
      <webElementGuid>9216cb0c-e4f9-4be0-91b8-1e7f631836cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>cbc0e373-8e71-47e4-b79e-2bf910004155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>b786897a-315e-45dc-b117-a696bc5fd77c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../App_Themes/TIPWeb/Images/Validate_16.gif</value>
      <webElementGuid>e0d68e8f-f8ad-472e-beaf-e867bddf79cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>84e56166-67d1-478a-977f-a3893d0e1941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>middle</value>
      <webElementGuid>6dee4b0f-0da7-445c-963f-8eb2612ea082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder1$TagNumberSaveImageButton&quot;, &quot;&quot;, true, &quot;TagSerialSearch&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>74e2f15e-f05b-426a-8c9a-c3ca35bfe5b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_TagNumberSaveImageButton&quot;)</value>
      <webElementGuid>9bbc5e4e-6c89-40ab-9fb6-fcbd128b53e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/QC Zebra/QC modal objects/iframe_Quick Collect_RadWindowQuickCollect</value>
      <webElementGuid>107ec52a-b6b2-4161-b33d-131547147d48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder1_TagNumberSaveImageButton']</value>
      <webElementGuid>ac3e7351-1e38-41d6-b95f-8b28d34dff05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder1_PartTwo']/div/table/tbody/tr/td/div[3]/table/tbody/tr/td[2]/input[2]</value>
      <webElementGuid>e083b2ee-c6bd-4826-9e1b-b7c969c7321b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/tbody/tr/td[2]/input[2]</value>
      <webElementGuid>ec3ce2b7-9a0e-4cfa-ba90-e14e30f8ca2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder1$TagNumberSaveImageButton' and @id = 'ctl00_ContentPlaceHolder1_TagNumberSaveImageButton' and @title = 'Save' and @src = '../App_Themes/TIPWeb/Images/Validate_16.gif' and @alt = 'Save']</value>
      <webElementGuid>0f0e7099-b43c-4e3e-bbcf-88deb5ced445</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
