<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Refresh</name>
   <tag></tag>
   <elementGuidId>b020c115-97ae-434a-aedb-7b2deea647fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_RoomResetImageButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder1_RoomResetImageButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13076274-63db-4f8b-bc47-be7a8e15e88c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>3cc21be3-b611-4579-ba20-a3d7cf561ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$RoomResetImageButton</value>
      <webElementGuid>3db56426-6eeb-4415-a044-8da28d9ead2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_RoomResetImageButton</value>
      <webElementGuid>ab456034-6e1e-442e-a8ae-81a5797cff6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>94ee2627-4476-4ead-83a2-1ecec1cbf058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Reset</value>
      <webElementGuid>bf9c0aa4-4457-441e-b61d-352afffcb466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../App_Themes/TIPWeb/Images/Reset_16.gif</value>
      <webElementGuid>7a907859-07c8-4a78-8ac0-e3f5349ba2d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Reset</value>
      <webElementGuid>c870953d-749f-4453-a147-c6203c7647a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>middle</value>
      <webElementGuid>d55732dd-b296-498f-a160-a7c2b9695c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_RoomResetImageButton&quot;)</value>
      <webElementGuid>c0cecf13-4ede-409b-a734-6a09c68597c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/QC Zebra/QC modal objects/iframe_Quick Collect_RadWindowQuickCollect</value>
      <webElementGuid>2a8ecf03-08df-4c68-a0af-06b2a1ef0e9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder1_RoomResetImageButton']</value>
      <webElementGuid>6a995899-e438-43d0-98db-5546f74a62fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder1_PanelRoom']/table/tbody/tr/td[2]/input[5]</value>
      <webElementGuid>3f1ec0c2-692f-4e0e-869a-285dcdb4e753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input[5]</value>
      <webElementGuid>15f89c06-6d52-4847-bc9b-1e75a8d48d11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder1$RoomResetImageButton' and @id = 'ctl00_ContentPlaceHolder1_RoomResetImageButton' and @title = 'Reset' and @src = '../App_Themes/TIPWeb/Images/Reset_16.gif' and @alt = 'Reset']</value>
      <webElementGuid>8c29c7c3-9d83-4519-a0c7-562ccf6c825a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
