<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Destination</name>
   <tag></tag>
   <elementGuidId>0af84a21-018d-4bea-9faa-c906db6d6e8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th.rgHeader.rgHeaderOver</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ctl00_ContentPlaceHolder1_RadGridHistory_ctl00']/thead/tr/th[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>f2909ce9-8020-49c6-98f7-71dc9d1f8c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>80dd5dfe-8ab6-47e7-8070-c7d257963a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rgHeader rgHeaderOver</value>
      <webElementGuid>58300558-5a5d-4a3e-8d6e-398875b90b85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Destination</value>
      <webElementGuid>8eabf66f-4d5b-48c1-ba86-a447ca9d9a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_RadGridHistory_ctl00&quot;)/thead[1]/tr[1]/th[@class=&quot;rgHeader rgHeaderOver&quot;]</value>
      <webElementGuid>da48b393-9112-4163-b214-210d60f6309d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/QC Zebra/QC modal objects/iframe_Quick Collect_RadWindowQuickCollect</value>
      <webElementGuid>d8fd68d4-6e40-4279-adcd-e7fcb0249ef7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder1_RadGridHistory_ctl00']/thead/tr/th[4]</value>
      <webElementGuid>31c449c1-58ef-4d4d-8e1e-edc339ccc5fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Source'])[1]/following::th[1]</value>
      <webElementGuid>ce98f8c3-c1b0-4e9a-8ccb-6008718ad7b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tag'])[1]/following::th[2]</value>
      <webElementGuid>9e5102db-8fb7-462c-af75-df295d218fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reports'])[1]/preceding::th[1]</value>
      <webElementGuid>f62ba0f0-d375-4571-b46a-2dc586a93200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[4]</value>
      <webElementGuid>2615dac1-76ca-4110-8d70-732fdc2d3c23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Destination' or . = 'Destination')]</value>
      <webElementGuid>b8803144-85e7-4fc2-ae28-d149b3753a9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
