<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Quick Collect_RadWindowQuickCollect</name>
   <tag></tag>
   <elementGuidId>9f255edb-fd79-4714-9475-a15aa7132235</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;RadWindowQuickCollect&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='RadWindowQuickCollect']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>3405f1ca-a878-4e07-998b-d96283d4caeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RadWindowQuickCollect</value>
      <webElementGuid>fee11934-583d-4ac1-b208-ef94cfef29f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/TIPWebIT/InventoryManagement/QuickCollect.aspx?Tag=157099&amp;Type=3&amp;rwndrnd=0.5284841802302246</value>
      <webElementGuid>49aad1ef-69ea-4ac6-ae8c-c82f8b2dde68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>70b34cf4-8edf-4e9f-9f1a-55e0fc300c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RadWindowWrapper_ctl00_RadWindowQuickCollect&quot;)/table[@class=&quot;rwTable&quot;]/tbody[1]/tr[@class=&quot;rwContentRow&quot;]/td[@class=&quot;rwWindowContent rwExternalContent&quot;]/iframe[1]</value>
      <webElementGuid>df582c7a-7105-4405-9a97-a90b98af7e9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='RadWindowQuickCollect']</value>
      <webElementGuid>970811df-eb29-4331-a4f4-9ead469e9abe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RadWindowWrapper_ctl00_RadWindowQuickCollect']/table/tbody/tr[2]/td[2]/iframe</value>
      <webElementGuid>df261d2d-5f4b-49c8-b468-1460c2583797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>130698f7-f083-4443-af7e-373d81759a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'RadWindowQuickCollect' and @src = '/TIPWebIT/InventoryManagement/QuickCollect.aspx?Tag=157099&amp;Type=3&amp;rwndrnd=0.5284841802302246']</value>
      <webElementGuid>c1bff580-1fcc-4829-b017-6f1248e114a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
