<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>53f74e5a-5e8d-4010-93eb-c06ee7b6b3b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_ContentPlaceHolder1_RadDock3_T']/ul/li[2]/a/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ctl00_ContentPlaceHolder1_RadDock3_T&quot;)/ul[@class=&quot;rdCommands&quot;]/li[2]/a[1]/span[@class=&quot;rdCustom&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7bc6d28b-e1a0-4938-a818-6d53ea05e4a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rdCustom</value>
      <webElementGuid>98acc7cc-6fd3-4b29-930f-4d2d204608d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>82ff7ac7-53e5-45ba-a073-696b002d5f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_RadDock3_T&quot;)/ul[@class=&quot;rdCommands&quot;]/li[2]/a[1]/span[@class=&quot;rdCustom&quot;]</value>
      <webElementGuid>4c4180e8-3d1e-4119-bda1-a90b16d5e9d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder1_RadDock3_T']/ul/li[2]/a/span</value>
      <webElementGuid>4ddd80b4-32f6-4d35-8cfa-315e6741e18c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications'])[1]/following::span[2]</value>
      <webElementGuid>0ca1f267-eefe-431b-ade5-4abff93c5fe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transfer'])[2]/following::span[3]</value>
      <webElementGuid>e7f4f727-9675-4ef1-b8f5-66660cb622af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='District Audit Notifications'])[1]/preceding::span[1]</value>
      <webElementGuid>466bd693-6b64-43e1-a8ad-fa922defd033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Audits Due Today:'])[1]/preceding::span[2]</value>
      <webElementGuid>15cce39d-ff8c-4461-bd2b-f51ff7a14a4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/div/div/table/tbody/tr/td[2]/div/ul/li[2]/a/span</value>
      <webElementGuid>5c9f4b6f-1497-429a-875e-820ac20f90aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' ' or . = ' ')]</value>
      <webElementGuid>acd46c84-359c-4e72-9874-179abc0db8b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
