<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_tipweb-test-user</name>
   <tag></tag>
   <elementGuidId>465a14be-c891-4070-8b70-62c3c147e715</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_RadMenuUserOptions']/ul/li/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.rmLink.rmRootLink.rmFocused > span.rmText.rmExpandDown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8cf91775-4537-42e7-b628-241815b9c8a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rmText rmExpandDown</value>
      <webElementGuid>bb4425a8-989f-419a-8fcd-19b73b4445da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>tipweb-test-user</value>
      <webElementGuid>e811a517-782c-453c-95af-6b1363cef4a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_RadMenuUserOptions&quot;)/ul[@class=&quot;rmRootGroup rmToggleHandles rmHorizontal&quot;]/li[@class=&quot;rmItem rmFirst rmLast&quot;]/a[@class=&quot;rmLink rmRootLink rmFocused&quot;]/span[@class=&quot;rmText rmExpandDown&quot;]</value>
      <webElementGuid>2198c83e-2ac6-45c1-a8d1-a7c01658b44f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_RadMenuUserOptions']/ul/li/a/span</value>
      <webElementGuid>85c9456e-9502-42d9-ab49-0efb59a14ee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/following::span[1]</value>
      <webElementGuid>33aef8b1-1490-4c42-a625-17a9a283487b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Done'])[1]/following::span[1]</value>
      <webElementGuid>472fd2ca-934f-4c38-9897-0b163b3f89bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle'])[1]/preceding::span[1]</value>
      <webElementGuid>688e520e-0c9b-4bfa-94b6-497bd6809531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile Settings'])[1]/preceding::span[3]</value>
      <webElementGuid>a95fa44b-93c5-43c8-9728-6958107d8c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='tipweb-test-user']/parent::*</value>
      <webElementGuid>c797375c-d35e-4358-a1ff-5a6e559e5e83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li/a/span</value>
      <webElementGuid>d79f67e3-da0c-4401-9d95-cefebe08c00e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'tipweb-test-user' or . = 'tipweb-test-user')]</value>
      <webElementGuid>c54a63e6-0139-4028-be2e-299b5fa6b7c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
