<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gear_</name>
   <tag></tag>
   <elementGuidId>35a0a366-2e65-45aa-94c2-77756ad6a872</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[2]/td/div/div/div/table/tbody/tr/td[2]/div/ul/li[2]/a/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'rdCustom']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1b3a8ffc-672d-48bf-bd04-bb00db522fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rdCustom</value>
      <webElementGuid>3e0ac3c9-6df5-4764-a4cd-d8032e9e6912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>f8a16b8e-27a2-4dde-90a4-b6baa972e24c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_RadDock3_T&quot;)/ul[@class=&quot;rdCommands&quot;]/li[2]/a[1]/span[@class=&quot;rdCustom&quot;]</value>
      <webElementGuid>720d2191-8310-4b2e-bc53-8df8dc0db9e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder1_RadDock3_T']/ul/li[2]/a/span</value>
      <webElementGuid>3d472a2d-a1bf-452b-ab13-4b68a4d357a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications'])[1]/following::span[2]</value>
      <webElementGuid>dd0e3443-11bb-4228-9fc5-43535d018bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download .CSV'])[2]/following::span[3]</value>
      <webElementGuid>36513ad5-9319-439f-9f6b-480eb5c98bc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='District Audit Notifications'])[1]/preceding::span[1]</value>
      <webElementGuid>4258aac1-87fe-4831-a455-f1e6fff5ef4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Audits Due Today:'])[1]/preceding::span[2]</value>
      <webElementGuid>14254551-3f0f-46cf-b63d-dad59a19418a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/div/div/table/tbody/tr/td[2]/div/ul/li[2]/a/span</value>
      <webElementGuid>8e040433-4aef-46a0-8e93-459e4ee0e9c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' ' or . = ' ')]</value>
      <webElementGuid>6c40ec3c-2ec9-4c2f-814f-5f7cd05c9141</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
