<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Close_RadWindowDashboardConfiguration</name>
   <tag></tag>
   <elementGuidId>2e668a94-8aa3-4a1f-b502-c293ceb53fc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='RadWindowDashboardConfiguration']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;RadWindowDashboardConfiguration&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>6a025cf9-392b-4f0a-b743-b49c9c57dbed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RadWindowDashboardConfiguration</value>
      <webElementGuid>54c7561e-691d-4a42-b012-f5fdef551dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/TIPWebIT/DashboardControls/UCConfigurationManagement.aspx?dockUniqueName=RadDockZone3&amp;Mode=Edit&amp;rwndrnd=0.92277576329075</value>
      <webElementGuid>dc6ba147-740d-4d47-aa68-2cf14a2a3c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1d66786a-180b-4768-b745-5f3441cbe6af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RadWindowWrapper_ctl00_ContentPlaceHolder1_RadWindowDashboardConfiguration&quot;)/table[@class=&quot;rwTable&quot;]/tbody[1]/tr[@class=&quot;rwContentRow&quot;]/td[@class=&quot;rwWindowContent rwExternalContent&quot;]/iframe[1]</value>
      <webElementGuid>36a7b4da-b620-4ac1-9002-4809280dc941</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='RadWindowDashboardConfiguration']</value>
      <webElementGuid>50ef3cd0-1633-4109-afee-7b366a0f905f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RadWindowWrapper_ctl00_ContentPlaceHolder1_RadWindowDashboardConfiguration']/table/tbody/tr[2]/td[2]/iframe</value>
      <webElementGuid>845e02f4-37e5-4112-9c33-8ab85ff6ec19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>2cccb313-4343-45d1-986a-e54e417f334a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'RadWindowDashboardConfiguration' and @src = '/TIPWebIT/DashboardControls/UCConfigurationManagement.aspx?dockUniqueName=RadDockZone3&amp;Mode=Edit&amp;rwndrnd=0.92277576329075']</value>
      <webElementGuid>c9ea92b0-d3e2-4cff-af92-f5343c93c8d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
