<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Save</name>
   <tag></tag>
   <elementGuidId>4515c5f0-940f-4847-923b-2c88abb009b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/div/div[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_Notifications_ImageButtonSaveDashboardConfiguration</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca720ab2-b04f-45ef-9d36-0255c02c01e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>815da5ff-6e5a-4122-bb30-c93666afb2fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$Notifications$ImageButtonSaveDashboardConfiguration</value>
      <webElementGuid>0d8755b4-6c2a-4298-8636-ef00b989eeef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_Notifications_ImageButtonSaveDashboardConfiguration</value>
      <webElementGuid>1cd60d71-eb09-454d-92f9-4f7b5ac910b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>c3fd6edd-abca-4b44-9067-46bf17241ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../App_Themes/TIPWeb/Images/Save.gif</value>
      <webElementGuid>cf18345b-8a6c-4a95-b7f2-eb610a6672c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>44bc82b1-704a-4113-ae2e-ea6191a89766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder1$Notifications$ImageButtonSaveDashboardConfiguration&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>2a63f602-3adc-469d-8839-06a52a40c8d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_Notifications_ImageButtonSaveDashboardConfiguration&quot;)</value>
      <webElementGuid>7084bd2a-cbbd-4f34-a490-07d58529adc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIPWebIT/Add Notifications/iframe_Close_RadWindowDashboardConfiguration</value>
      <webElementGuid>170352e6-f7da-4ce2-be2d-0f216b667566</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder1_Notifications_ImageButtonSaveDashboardConfiguration']</value>
      <webElementGuid>6cb263cb-b63f-4b4e-8f27-964674ec1bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder1_Notifications_ConfigurationView']/div[2]/input</value>
      <webElementGuid>a2e4dc43-e093-4cc8-8650-172a63a99e31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>433a5ab4-083c-4c84-816a-42c5cf6887ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder1$Notifications$ImageButtonSaveDashboardConfiguration' and @id = 'ctl00_ContentPlaceHolder1_Notifications_ImageButtonSaveDashboardConfiguration' and @title = 'Save' and @src = '../App_Themes/TIPWeb/Images/Save.gif' and @alt = 'Save']</value>
      <webElementGuid>45fdf426-3b4d-494a-b78e-30d69efdb560</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
