<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Close</name>
   <tag></tag>
   <elementGuidId>2ab60af1-380a-44d0-8528-e8520d724181</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='RadWindowWrapper_ctl00_RadWindowLocationImport']/table/tbody/tr/td[2]/table/tbody/tr/td[3]/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.rwCloseButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>de43abc9-1392-4055-b8b7-034262e9e43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>2af8bcbc-f156-4d02-b691-6cd57ba0356a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rwCloseButton</value>
      <webElementGuid>e84f5c0e-f6b4-488c-a4fb-d5268da06018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>8a58e12b-5790-48cb-af0d-9272d347f91c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>ac0f5f22-9f1c-416c-b2c7-54f9cc1b468d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RadWindowWrapper_ctl00_RadWindowLocationImport&quot;)/table[@class=&quot;rwTable&quot;]/tbody[1]/tr[@class=&quot;rwTitleRow&quot;]/td[@class=&quot;rwTitlebar&quot;]/table[@class=&quot;rwTitlebarControls&quot;]/tbody[1]/tr[1]/td[3]/ul[@class=&quot;rwControlButtons&quot;]/li[1]/a[@class=&quot;rwCloseButton&quot;]</value>
      <webElementGuid>c8f37084-6b51-4476-9ce8-5ee770cd74c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RadWindowWrapper_ctl00_RadWindowLocationImport']/table/tbody/tr/td[2]/table/tbody/tr/td[3]/ul/li/a</value>
      <webElementGuid>d88f5a0d-d188-47bb-a8cd-75fa3fa02c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location Import'])[1]/following::a[1]</value>
      <webElementGuid>b55bb035-b009-4704-b9d8-0fc3ab9213de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='status label'])[1]/preceding::a[1]</value>
      <webElementGuid>591159c5-d1c1-474d-9a76-1c3d41478f51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0);')]</value>
      <webElementGuid>21d69767-d2a8-4c27-b580-f2e95ba7637a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>7694b5bc-00ce-4541-ba22-d53ad544b80c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @title = 'Close' and (text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>8dea698e-9645-4dc6-9e62-738e3c21c192</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
