<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_here</name>
   <tag></tag>
   <elementGuidId>b6629b80-1175-47e1-bded-c675bb1e9dc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder1_templateUrl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_templateUrl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e028b972-c855-4e20-96b6-4bf2738f9da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../Lib/Location Import Template.xlsx</value>
      <webElementGuid>14b88bf1-af7b-463d-812a-7c832380d5b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_templateUrl</value>
      <webElementGuid>eb730d2a-22f4-42a9-846d-c72ee11a5e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>here</value>
      <webElementGuid>7fe338cf-21c9-4284-a493-f70511f6b36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_templateUrl&quot;)</value>
      <webElementGuid>1b206424-9333-4ca3-8a5e-4220fdb3d58c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIPWebIT/Location Import/iframe_Close_RadWindowLocationImport</value>
      <webElementGuid>eab5e5af-e48a-47c0-8bcd-5ee6b69e07ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder1_templateUrl']</value>
      <webElementGuid>ebaea661-69e2-45c2-b11f-3cc2f655a408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder1_PanelContent']/div/div[2]/div/div[2]/table/tbody/tr/td/div/div/b/a</value>
      <webElementGuid>529d7e97-3da9-4920-9752-99fdcc2cb95b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'here')]</value>
      <webElementGuid>196bf029-fb1a-444d-9291-0c354bd8fd96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drop files here'])[1]/preceding::a[1]</value>
      <webElementGuid>cb22aae2-f7fa-4118-b5b6-7d22ddcc7c04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Import Details'])[1]/preceding::a[1]</value>
      <webElementGuid>21da220a-2f52-4eb8-b5f9-23a9e6151e24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='here']/parent::*</value>
      <webElementGuid>f5d4cc09-673d-4ca7-8486-0ee3d4e345a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '../Lib/Location Import Template.xlsx')]</value>
      <webElementGuid>96060c25-2b85-4a69-8bdd-0e8213feb4ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b/a</value>
      <webElementGuid>ba2b0ff1-b79d-4e41-9ad0-7023cd3195b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '../Lib/Location Import Template.xlsx' and @id = 'ctl00_ContentPlaceHolder1_templateUrl' and (text() = 'here' or . = 'here')]</value>
      <webElementGuid>bfe3c40e-b059-49d3-985d-c56dfcba276a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
