<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Location Import</name>
   <tag></tag>
   <elementGuidId>d695f678-6e7d-4396-a9ea-de3912893983</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_LinkButtontLocationImport']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_LinkButtontLocationImport</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>63b2cb4c-af9d-4165-bf0f-950f00569dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>OpenWindowNav('ImporterManagement/BulkLocationUpdateTool.aspx','RadWindowLocationImport','Location Import'); return false;</value>
      <webElementGuid>ef9ba0f7-3706-4354-bd3b-f6e5ece5d429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_LinkButtontLocationImport</value>
      <webElementGuid>a1ac15cb-4a71-4545-b3a4-8a1d8f46789e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$LinkButtontLocationImport','')</value>
      <webElementGuid>29bac8fb-db1b-4df6-90d9-a71c446ee423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Location Import</value>
      <webElementGuid>db032677-b3c0-4e8b-8d69-1120cd2270fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_LinkButtontLocationImport&quot;)</value>
      <webElementGuid>409426ae-3f1a-421e-8b94-2e5a2f644762</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_LinkButtontLocationImport']</value>
      <webElementGuid>acafbdbe-dd60-43b7-aa9a-fbca8a031771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ctl00_TableRowLocationImport']/td/a</value>
      <webElementGuid>6863dade-a4a1-429d-95ab-35ea436f5559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Location Import')]</value>
      <webElementGuid>d66729d5-8e51-4f5e-8142-01ba75a0defb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status Import'])[1]/following::a[1]</value>
      <webElementGuid>6165fc50-0e77-433b-b5bd-f0a2ca005ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RFID Association'])[1]/following::a[2]</value>
      <webElementGuid>2b0e4e70-9b24-4407-acdb-8260e18ea03a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transfer History'])[1]/preceding::a[1]</value>
      <webElementGuid>2ef3fe82-f46f-4fca-aa16-e1be4c1a82ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Management'])[1]/preceding::a[2]</value>
      <webElementGuid>d31d0b58-04a6-46da-adbb-4762bdc32fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Location Import']/parent::*</value>
      <webElementGuid>4b787678-b587-42ff-901b-7aac33178129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$LinkButtontLocationImport','')&quot;)]</value>
      <webElementGuid>aaed473c-4e0a-4305-b61b-e00c8990c70f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td/a</value>
      <webElementGuid>1e42bcc9-3a39-49ed-be62-d0da88433058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_LinkButtontLocationImport' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$LinkButtontLocationImport&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Location Import' or . = 'Location Import')]</value>
      <webElementGuid>a5fb40f3-3a9b-4016-9096-77c88e5c3e0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
