<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Close_RadWindowLocationImport</name>
   <tag></tag>
   <elementGuidId>f51a1738-a66f-45fc-83bf-23f46bfcc343</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='RadWindowLocationImport']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;RadWindowLocationImport&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>5b51b16d-1586-4cf9-b3e0-1d6c468e4ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RadWindowLocationImport</value>
      <webElementGuid>f13955d3-9abe-455a-8b64-2e087d7fe123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/TIPWebIT/ImporterManagement/BulkLocationUpdateTool.aspx?rwndrnd=0.6381739930455772</value>
      <webElementGuid>ac9567b2-e82b-4af1-bb20-cc17388d4a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7decf909-b7ac-4330-9a27-1bd14a303fe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RadWindowWrapper_ctl00_RadWindowLocationImport&quot;)/table[@class=&quot;rwTable&quot;]/tbody[1]/tr[@class=&quot;rwContentRow&quot;]/td[@class=&quot;rwWindowContent rwExternalContent&quot;]/iframe[1]</value>
      <webElementGuid>3b6d4c67-b1fd-488c-b8ce-410fc2bc44fd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
