<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Successful Ticket Creations205</name>
   <tag></tag>
   <elementGuidId>a036d14c-bbeb-4d2e-be4e-afd1d2d0eb72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder1_RadDock3_C_ctl00_AuditNotifications1_LinkButtonSuccessful']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Successful Ticket Creations' or . = 'Successful Ticket Creations')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_RadDock3_C_ctl00_AuditNotifications1_LinkButtonSuccessful</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0306cb13-b0c5-4abc-94f4-18329f075ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>OpenWindowNav('HelpDeskManagment/TicketCreationSummary.aspx?Status=0','RadWindowTicketCreationSummary'); return false;</value>
      <webElementGuid>8500d608-4772-4818-9e98-a58f277af082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_RadDock3_C_ctl00_AuditNotifications1_LinkButtonSuccessful</value>
      <webElementGuid>9134a769-6210-434e-a32d-0c74f8e836a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>BoldGreenText</value>
      <webElementGuid>80d8f416-5293-4dea-8d2d-cdd6597e4c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$ContentPlaceHolder1$RadDock3$C$ctl00$AuditNotifications1$LinkButtonSuccessful','')</value>
      <webElementGuid>af6bc7f3-e6b1-4a91-9958-22b89f3b72f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Successful Ticket Creations</value>
      <webElementGuid>dd0c95d1-a6ef-43a6-92c5-3191ea923f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_RadDock3_C_ctl00_AuditNotifications1_LinkButtonSuccessful&quot;)</value>
      <webElementGuid>c6df1634-22a5-4d0a-bd9c-f905dc23b621</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder1_RadDock3_C_ctl00_AuditNotifications1_LinkButtonSuccessful']</value>
      <webElementGuid>0156fd7c-df70-46d9-b988-4c15d58f1465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder1_RadDock3_C_ctl00_AuditNotifications1_PanelTicketNotification']/table/tbody/tr[3]/td/a</value>
      <webElementGuid>5abafc3a-bcb8-416d-9cfe-83bba6c26503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Successful Ticket Creations: 205')]</value>
      <webElementGuid>6fec6404-f80b-482b-a05e-13ab7999997d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HelpDesk Ticket Creation Notifications'])[1]/following::a[1]</value>
      <webElementGuid>dbd34bdf-af73-4103-bdf8-6e0e90ecc667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Audits Past Due:'])[1]/following::a[2]</value>
      <webElementGuid>07e2057d-562b-49cf-aca5-284e7e8de15c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Failed Ticket Creations: 2'])[1]/preceding::a[1]</value>
      <webElementGuid>4ef26ecc-ef7a-4391-8f96-acc3cff0293f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending Ticket Creations: 0'])[1]/preceding::a[2]</value>
      <webElementGuid>cd9612f7-4005-4ca1-adca-28c2ed1b7274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Successful Ticket Creations: 205']/parent::*</value>
      <webElementGuid>184e04ea-3ff2-4264-91df-9d8fdc279a5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$ContentPlaceHolder1$RadDock3$C$ctl00$AuditNotifications1$LinkButtonSuccessful','')&quot;)]</value>
      <webElementGuid>00970294-069e-4da7-aa23-c93ee46144ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/div/div[2]/table/tbody/tr[3]/td/a</value>
      <webElementGuid>2db80210-9e8e-4c80-b8eb-f8925478385f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ContentPlaceHolder1_RadDock3_C_ctl00_AuditNotifications1_LinkButtonSuccessful' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$ContentPlaceHolder1$RadDock3$C$ctl00$AuditNotifications1$LinkButtonSuccessful&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Successful Ticket Creations: 205' or . = 'Successful Ticket Creations: 205')]</value>
      <webElementGuid>781b014e-bde2-4460-9664-b60aac616ccc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
