<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AM Logo</name>
   <tag></tag>
   <elementGuidId>68e09c38-7fa5-44fc-954e-fc0f418d2edf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;TIPWebIT Log On Logo&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ctl00_ContentPlaceHolder1_LogOnLogoLabel']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2341858c-b958-4747-97d2-e42bf5650eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>TIPWebIT Log On Logo</value>
      <webElementGuid>ddead73d-8a03-4337-bfd5-7cd952484e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>App_Themes/TIPWeb/Images/TIPWeb-IT-Logo-shadow.gif</value>
      <webElementGuid>357d0792-9e46-441a-82d5-a62674beb7aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_LogOnLogoLabel&quot;)/img[1]</value>
      <webElementGuid>a4b38f9f-f13a-44db-886e-c81f3de66799</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='ctl00_ContentPlaceHolder1_LogOnLogoLabel']/img</value>
      <webElementGuid>f6e7701f-a83d-43dd-a420-42cd37ac9177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username:'])[1]/preceding::img[1]</value>
      <webElementGuid>42b69fe6-a9a7-45dc-869f-5df88c2a0495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username required'])[1]/preceding::img[1]</value>
      <webElementGuid>f90f7ed9-cf13-4318-b878-560636754e54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='TIPWebIT Log On Logo']</value>
      <webElementGuid>f5187db7-4639-4118-a67b-ae862a938451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>4e7a541b-038a-4074-abee-869eac6f0cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'TIPWebIT Log On Logo' and @src = 'App_Themes/TIPWeb/Images/TIPWeb-IT-Logo-shadow.gif']</value>
      <webElementGuid>7f966f0a-af70-4c22-b780-4a1815339351</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
