<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ActionDD</name>
   <tag></tag>
   <elementGuidId>563fde73-db43-4fbe-ac65-ba5b8ec12e2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_TagInformation1_RadComboBoxActions_Arrow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bbfa8a42-faa0-4ba5-97a3-8c4eaa97fe96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_TagInformation1_RadComboBoxActions_Arrow</value>
      <webElementGuid>0ff3dc0c-5ce8-4a9a-9e4c-5a6f1de22e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>efd903d4-63b8-4d10-a949-9c17ddfa6b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_TagInformation1_RadComboBoxActions_Arrow&quot;)</value>
      <webElementGuid>2861039b-6018-430e-90fe-8061583b75be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/QC Zebra/iframe_Close_RadWindowTagInfo</value>
      <webElementGuid>9c64c43d-783e-4799-b1be-c623646f9591</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder1_TagInformation1_RadComboBoxActions_Arrow']</value>
      <webElementGuid>e9c90cda-34b0-462e-85d2-5c5dcffd76a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder1_TagInformation1_RadComboBoxActions']/table/tbody/tr/td[2]/a</value>
      <webElementGuid>8c050d5a-8531-4637-946b-a6d32caa1c96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'select')]</value>
      <webElementGuid>f7db54f4-b299-4584-a52a-c831e0ec092a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick Verify'])[1]/following::a[1]</value>
      <webElementGuid>1daa1a85-c58a-4142-ba7f-5e725381fcae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tag/Serial:'])[1]/following::a[2]</value>
      <webElementGuid>b54d71b1-8785-4bbb-8002-b2aaccfda376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--- Change Location ---'])[1]/preceding::a[1]</value>
      <webElementGuid>e293fd9f-17ad-4f14-b818-2829be213270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collect'])[1]/preceding::a[1]</value>
      <webElementGuid>8f2ba51b-9850-4c39-b245-69c5ea68d719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='select']/parent::*</value>
      <webElementGuid>6b5587d7-b901-40d9-8285-5ab24774f599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>dab35958-3a12-4536-ba49-84d0221ac7c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ContentPlaceHolder1_TagInformation1_RadComboBoxActions_Arrow' and (text() = 'select' or . = 'select')]</value>
      <webElementGuid>a04af146-02f9-46ec-9ab6-f2bce4c909bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
