<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tag  Serial_ctl00_RadSearchBoxInfo</name>
   <tag></tag>
   <elementGuidId>ae081b59-dcca-4f2a-bf75-1a04ab1321ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_RadSearchBoxInfo_Input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_RadSearchBoxInfo_Input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>63c6101c-88ce-4a42-89b0-05a2b2e0c731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rsbInput radPreventDecorate rsbEmptyMessage</value>
      <webElementGuid>5d48ccab-50b4-48e4-a2eb-3cecd254df2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c363b87d-b414-4dee-8218-c8f32631eb17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search Tag or Serial Number</value>
      <webElementGuid>daae93f9-5aa6-43d8-abcb-0a5c77009f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00_RadSearchBoxInfo</value>
      <webElementGuid>c3f620e8-40ca-4538-ad1c-6c53f5a1e0bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_RadSearchBoxInfo_Input</value>
      <webElementGuid>5089c14a-edc4-49f7-b298-8c5a25c6885e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5465192c-f0c7-4a68-a091-e266990fa7bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_RadSearchBoxInfo_Input&quot;)</value>
      <webElementGuid>6aa083bb-bb35-43ea-9dd9-0d8d6a7de591</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_RadSearchBoxInfo_Input']</value>
      <webElementGuid>40c38cce-4822-44c0-b886-5675a281de55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_RadSearchBoxInfo']/span/input</value>
      <webElementGuid>310c61ed-d65e-4d27-b598-88476a311d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>5e038749-a670-468e-8827-c22e68632431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'ctl00_RadSearchBoxInfo' and @id = 'ctl00_RadSearchBoxInfo_Input']</value>
      <webElementGuid>ab6e274a-0073-45cd-bb62-51f3db8422af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
