<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Collect</name>
   <tag></tag>
   <elementGuidId>ac487a97-bc49-4226-8a15-e10d3f9caf90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.rcbHovered</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>8d55e144-7c1b-4cbd-a2a9-538d9cc49ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rcbHovered</value>
      <webElementGuid>7b938b5c-d8b8-41d5-8d03-dd174bcbf529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Collect</value>
      <webElementGuid>e54754c2-4de9-458e-a9f0-146f399a9ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_TagInformation1_RadComboBoxActions_DropDown&quot;)/div[@class=&quot;rcbScroll rcbWidth&quot;]/ul[@class=&quot;rcbList&quot;]/li[@class=&quot;rcbHovered&quot;]</value>
      <webElementGuid>274825b0-807a-4dff-bd9a-0b95736d08af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/QC Zebra/iframe_Close_RadWindowTagInfo</value>
      <webElementGuid>1a44b59b-fd91-4858-af2e-b7ba33ac54d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder1_TagInformation1_RadComboBoxActions_DropDown']/div/ul/li[2]</value>
      <webElementGuid>9be75756-e82a-470e-9d4e-521adf35c29e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--- Change Location ---'])[1]/following::li[1]</value>
      <webElementGuid>48b96dea-77dd-4440-a443-cef1598a66f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--- View Report ---'])[1]/preceding::li[1]</value>
      <webElementGuid>0668da1e-11c8-4dd9-97e4-a145e8faa586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tag Lifecycle'])[1]/preceding::li[2]</value>
      <webElementGuid>38d71fd4-1ea9-4263-9006-9a832163aaf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Collect']/parent::*</value>
      <webElementGuid>d56b6373-647e-4cff-b58b-a1d36a4eaea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]</value>
      <webElementGuid>274871c7-ad4e-41a3-8d8c-7c4d1205e39c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Collect' or . = 'Collect')]</value>
      <webElementGuid>ae5fe6dd-454f-44d0-8036-495fd8738e98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
