<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tag  BeginSearch</name>
   <tag></tag>
   <elementGuidId>5f2eda2f-bb28-4a3e-8120-0399a8622b58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.rsbIcon.rsbIconSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_RadSearchBoxInfo']/span/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7f396481-7874-45bc-b111-f6dd35745d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rsbIcon rsbIconSearch</value>
      <webElementGuid>82c958f4-8c6a-49b8-9b9d-cc5bed387f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_RadSearchBoxInfo&quot;)/span[@class=&quot;rsbInner rsbFocused rsbHovered&quot;]/button[@class=&quot;rsbButton rsbButtonSearch rsbHovered&quot;]/span[@class=&quot;rsbIcon rsbIconSearch&quot;]</value>
      <webElementGuid>1a9c2916-d369-4de5-bb7a-9239ac3e110c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_RadSearchBoxInfo']/span/button/span</value>
      <webElementGuid>c0f832a4-5a6c-4f51-8bd7-258b62c0b70c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tag / Serial'])[1]/following::span[3]</value>
      <webElementGuid>450a67b3-3970-46e6-9c69-132ab73beb80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reconcile Audits'])[1]/following::span[7]</value>
      <webElementGuid>88ac8614-9588-44f7-97aa-101a5cd3831d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tag / Serial'])[2]/preceding::span[1]</value>
      <webElementGuid>9240ab7f-dcc4-47f4-8ce7-fd33837ad26f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Staff'])[2]/preceding::span[1]</value>
      <webElementGuid>d5986fa1-6b18-491f-9d54-e9d2cb61b350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>7b1c4dde-8cc0-4081-a2ce-ad2ebd613992</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
