<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_DetailTab</name>
   <tag></tag>
   <elementGuidId>5f4c63d1-ddf8-4cea-b5b5-4e932e88616e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.rtsTxt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_ContentPlaceHolder1_TagInformation1_RadTabStripTagInfo']/div/ul/li/a/span/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>59beb939-7719-41ba-90ff-c0e4634acfe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rtsTxt</value>
      <webElementGuid>86e85399-bf0b-468a-91a0-9bc8111745f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Detail</value>
      <webElementGuid>9058d645-9223-404d-8aa6-5938139c38a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_TagInformation1_RadTabStripTagInfo&quot;)/div[@class=&quot;rtsLevel rtsLevel1&quot;]/ul[@class=&quot;rtsUL&quot;]/li[@class=&quot;rtsLI rtsFirst&quot;]/a[@class=&quot;rtsLink rtsSelected&quot;]/span[@class=&quot;rtsOut&quot;]/span[@class=&quot;rtsIn&quot;]/span[@class=&quot;rtsTxt&quot;]</value>
      <webElementGuid>f2ea55e3-1189-45de-b8ed-256b7e9203d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/QC Zebra/iframe_Close_RadWindowTagInfo</value>
      <webElementGuid>64d30f80-3a82-4c12-8740-78708d9caeb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder1_TagInformation1_RadTabStripTagInfo']/div/ul/li/a/span/span/span</value>
      <webElementGuid>f822d979-363b-4a35-a975-91c575acf191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tag Lifecycle'])[1]/following::span[4]</value>
      <webElementGuid>8354c74a-35ac-4c46-91d7-0ffca1ab3c71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--- View Report ---'])[1]/following::span[4]</value>
      <webElementGuid>51a728b0-dbcc-4876-8892-a8c09ebc0563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status History'])[1]/preceding::span[1]</value>
      <webElementGuid>abd412af-3f84-4646-8f1c-406d4c00c522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Audit History'])[1]/preceding::span[4]</value>
      <webElementGuid>58a9c3ab-a6a9-424f-94bc-4ad91a4babb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Detail']/parent::*</value>
      <webElementGuid>7b98b947-fa09-47bc-b27b-befe1311f7e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span</value>
      <webElementGuid>83213a0c-1a0f-456b-9809-d76bf9930392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Detail' or . = 'Detail')]</value>
      <webElementGuid>97638e97-3140-4d5f-ac10-81a9f44f33ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
