<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_LoginUserPassword</name>
   <tag></tag>
   <elementGuidId>4baadd92-fa5f-48a7-b016-f77981a33f5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LoginUser_Password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LoginUser_Password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41c01737-8321-4c80-a27c-28f700c6a309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LoginUser$Password</value>
      <webElementGuid>4889ea7c-e620-46fb-868c-583b98bb46d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>59114d0d-02d8-45c8-b765-01c9185ad7ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LoginUser_Password</value>
      <webElementGuid>78552b8f-3b13-4f09-83cf-60dd5a12d7ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>990faba3-7131-4598-9116-551890d7a625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LoginUser_Password&quot;)</value>
      <webElementGuid>97777e72-4f99-4211-a764-3ed4677987d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LoginUser_Password']</value>
      <webElementGuid>b3bd4810-f79e-443f-b9b6-56faecaf1238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginForm']/div[3]/div[3]/table/tbody/tr[2]/td[2]/p/input</value>
      <webElementGuid>ecfce39f-504c-4560-83cc-4a9f8017c316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password:'])[1]/following::input[1]</value>
      <webElementGuid>662d6dbf-62db-45a3-b71a-31dfc7fde574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::input[1]</value>
      <webElementGuid>36244b04-016c-42ce-b7d4-3b7edebb1f40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::input[1]</value>
      <webElementGuid>fbefaa1d-d4b8-47cd-b2e5-5bd021fc5601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'LoginUser_Password', '&quot;', ')')])[1]/preceding::input[2]</value>
      <webElementGuid>fb62c95f-d020-45a6-98c3-acb4f48d8d4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/p/input</value>
      <webElementGuid>49c8b2e5-d637-4045-9c30-03832f4c689e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'LoginUser$Password' and @type = 'password' and @id = 'LoginUser_Password']</value>
      <webElementGuid>aca08592-0d05-4690-b67e-ea7c3542a4fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
