<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__LoginUserLoginButton</name>
   <tag></tag>
   <elementGuidId>b5940d3e-0ded-4906-8dbd-3bc0969a4cea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LoginUser_LoginButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LoginUser_LoginButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>11c8bd1b-5a1c-4aab-8a3e-b394735dbb00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>19c748de-eec6-4c3c-87d6-3e89d2053f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LoginUser$LoginButton</value>
      <webElementGuid>e7d493d3-9b37-4b8c-b22a-fe75284c1f4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>9da4e8e6-e6d7-453d-804b-9d4a7f616410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;LoginUser$LoginButton&quot;, &quot;&quot;, true, &quot;LoginUserValidationGroup&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>16cf98e4-e4bd-40e4-b0f4-560270d9c466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LoginUser_LoginButton</value>
      <webElementGuid>2ef613a4-02e1-4354-a6b2-a2d6454a1d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LoginUser_LoginButton&quot;)</value>
      <webElementGuid>d2c2a7b5-e2da-49fa-a1ef-8efe354da50c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LoginUser_LoginButton']</value>
      <webElementGuid>601adc27-f689-4aa9-b1c0-77781d0b57f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginForm']/div[3]/div[3]/table/tbody/tr[3]/td/p/input</value>
      <webElementGuid>992e0880-4362-42a6-849c-b3bdd89c2cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::input[1]</value>
      <webElementGuid>cf8e1185-eba8-4dfd-9524-5679e6c1f16f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password:'])[1]/following::input[2]</value>
      <webElementGuid>bfe7569e-0f2d-43ee-b6b8-15dd9e31621e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'LoginUser_LoginButton', '&quot;', ')')])[1]/preceding::input[1]</value>
      <webElementGuid>b07532a6-6cf5-4e52-a601-537daae58e2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/p/input</value>
      <webElementGuid>a55d262c-23e3-4f9a-aa57-54c79fba2f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'LoginUser$LoginButton' and @id = 'LoginUser_LoginButton']</value>
      <webElementGuid>6b86dbe9-d16f-428e-92f5-fbb26c4d2ea5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
