<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User name_LoginUserUserName</name>
   <tag></tag>
   <elementGuidId>cae826f3-2f08-4a5c-b02e-65e758a492fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LoginUser_UserName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LoginUser_UserName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>089c41d5-db32-4684-a734-66db7b4344c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LoginUser$UserName</value>
      <webElementGuid>0028c172-a79e-4b92-8f5a-d7ddcf5903b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9d4c8f2d-47a7-4bdf-baf9-4b0685dcf3ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LoginUser_UserName</value>
      <webElementGuid>a63e3aae-d80c-4bfe-b780-16208fdf6cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>userName</value>
      <webElementGuid>fa9d7e82-5ede-4abc-bd8f-50d58127ef6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LoginUser_UserName&quot;)</value>
      <webElementGuid>640136f4-fa77-4b2b-93ce-3bb189776119</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LoginUser_UserName']</value>
      <webElementGuid>07225b9f-48b5-4ee6-be57-d2101d346d52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginForm']/div[3]/div[3]/table/tbody/tr/td[2]/p/input</value>
      <webElementGuid>43814ac2-5cab-49bf-9a78-7c165de13e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User name:'])[1]/following::input[1]</value>
      <webElementGuid>1a557074-8485-43d4-9699-2845b0ab0b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Single Sign On'])[2]/following::input[1]</value>
      <webElementGuid>5c6e4fd8-5791-4984-b03e-55f7a4fd1ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::input[1]</value>
      <webElementGuid>181525b4-e512-46f0-bed6-1f0a69c96e79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password:'])[1]/preceding::input[1]</value>
      <webElementGuid>763ccf70-78cc-48f4-8aa9-e6d4e572fec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>b80d572c-ee6d-4d0d-9e65-b282106b93cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'LoginUser$UserName' and @type = 'text' and @id = 'LoginUser_UserName']</value>
      <webElementGuid>116576b9-e086-4ada-922d-6b29f61787fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
