<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue</name>
   <tag></tag>
   <elementGuidId>125a9b2a-f7f6-4b54-9ba9-ea708ad208b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.sc-kPVwWT.duNpUs.sc-kpOJdX.eAgQMY</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0ef65d56-8345-4f2f-a83e-71fec80772a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-kPVwWT duNpUs sc-kpOJdX eAgQMY</value>
      <webElementGuid>ecfefa83-e82d-4e09-9f1a-daca555c6fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>aed43dee-e4a2-48c8-ad45-e04dbe7efd9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ce0e9b5e-731b-4598-9761-6d7f21b651c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>.0.1.0.2.1.0.3.0.0</value>
      <webElementGuid>3b1cf8d2-dab6-4dac-abe4-cfe30b6421fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>4015c581-9ded-4768-8668-573e0d094916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-fOKMvo iAWbas&quot;]/div[@class=&quot;sc-eerKOB iianGF&quot;]/div[@class=&quot;withConditionalBorder sc-emmjRN hXyKZO&quot;]/div[@class=&quot;sc-bnXvFD fhRaDj&quot;]/form[1]/div[@class=&quot;sc-bZQynM QzQWh&quot;]/div[@class=&quot;sc-gzVnrw bbllgR&quot;]/div[@class=&quot;sc-hwwEjo fNBmGS&quot;]/button[@class=&quot;sc-kPVwWT duNpUs sc-kpOJdX eAgQMY&quot;]</value>
      <webElementGuid>d7c17912-08e6-4235-bdb7-c35411cd98b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>de12b5f8-6a8d-4bc6-9e47-bd75236443e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div[3]/form/div/div[3]/div/button</value>
      <webElementGuid>ca304482-01d8-4921-9345-25307b268826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::button[1]</value>
      <webElementGuid>3fdeb3e4-1fd3-46cf-9756-75e86bf74cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not you?'])[1]/following::button[1]</value>
      <webElementGuid>4b40227f-5c62-4019-84f0-975160c941db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instructions'])[1]/preceding::button[1]</value>
      <webElementGuid>0bc4def5-8026-4360-a1a1-26146e1ca14a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>4b55c1d5-01d8-4f95-b2f6-3f13262f09bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>e2fd2f33-ef1b-443d-b663-83c13e84b830</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
