<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Continue</name>
   <tag></tag>
   <elementGuidId>18ff66a7-2626-4d02-9411-044a7f94b0d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.sc-kPVwWT.duNpUs.sc-kpOJdX.eAgQMY > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3e2b2bd6-e272-49a4-a3c2-67c0f0f9df94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>.0.1.0.2.1.0.2.0.0.0</value>
      <webElementGuid>7157ebf5-d2c2-4246-8f05-2dcf532896c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>78c4f57b-6e31-4a69-a7c6-a360791309ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-fOKMvo iAWbas&quot;]/div[@class=&quot;sc-eerKOB iianGF&quot;]/div[@class=&quot;withConditionalBorder sc-emmjRN hXyKZO&quot;]/div[@class=&quot;sc-bnXvFD fhRaDj&quot;]/form[1]/div[@class=&quot;sc-bZQynM QzQWh&quot;]/div[@class=&quot;sc-gzVnrw bbllgR&quot;]/div[@class=&quot;sc-hwwEjo fNBmGS&quot;]/button[@class=&quot;sc-kPVwWT duNpUs sc-kpOJdX eAgQMY&quot;]/span[1]</value>
      <webElementGuid>0a17b34d-ceb8-4ff6-80da-1c26a9e76d00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div[3]/form/div/div[3]/div/button/span</value>
      <webElementGuid>0d357d8f-f2f1-40d9-8660-fad12aaddba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remember me'])[1]/following::span[1]</value>
      <webElementGuid>65cf0aca-b55b-46b4-9550-35dd374cc65f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Address'])[1]/following::span[3]</value>
      <webElementGuid>d76f55d2-7158-4843-8b2d-48354944f46e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instructions'])[1]/preceding::span[1]</value>
      <webElementGuid>73c609cb-6738-4bb6-82b1-3f882d2f2d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password'])[1]/preceding::span[2]</value>
      <webElementGuid>eab7aad1-4493-484b-ba89-424010380b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>3f8764a9-3076-4266-b00e-a6c37fde03a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>9f41ea3e-7884-4882-bade-d3f1a92d5cce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>453d280b-7a16-4f4e-89dd-068394ecf2bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
