<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>New Postman Request(2)</name>
   <tag></tag>
   <elementGuidId>1c459013-4be6-42dc-ac4e-7ba3db5c417a</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;[\r\n    {\r\n        \&quot;ProductNumber\&quot;: 0, \r\n        \&quot;ProductName\&quot;: \&quot;20 UNIT NOTEBOOK STORAGE CART\&quot;,\r\n        \&quot;ProductDescription\&quot;: \&quot;20 UNIT NOTEBOOK STORAGE CART\&quot;,\r\n        \&quot;ProductType\&quot;: \&quot;Unspecified\&quot;,\r\n        \&quot;Model\&quot;: \&quot;None\&quot;,\r\n        \&quot;Manufacturer\&quot;: \&quot;None\&quot;,\r\n        \&quot;SuggestedPrice\&quot;: 1064.00,\r\n        \&quot;Notes\&quot;: \&quot;Hayes Integration 05/21/2018\&quot;,\r\n        \&quot;SKU\&quot;: \&quot;\&quot;,\r\n        \&quot;ProjectedLife\&quot;: 0,\r\n        \&quot;CustomField1\&quot;: null,\r\n        \&quot;CustomField2\&quot;: null,\r\n        \&quot;CustomField3\&quot;: null\r\n    }\r\n]&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>421ed162-3eed-4c7a-9a65-fe2d0d02ee2a</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>${TIPWebAPI_Bearer}</value>
      <webElementGuid>25ea7455-b7cc-4d82-ad08-8ea678af42aa</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>8.5.2</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${TIPWebAPI_Url}/api/Integrations/Products/UpsertProducts</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.TIPWebAPI_Url</defaultValue>
      <description></description>
      <id>86d53963-eec2-47d2-94f1-2ff2e95483e8</id>
      <masked>false</masked>
      <name>TIPWebAPI_Url</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.TIPWebAPI_Bearer</defaultValue>
      <description></description>
      <id>b3c3d717-90ea-4c18-930e-7547689dbe5d</id>
      <masked>false</masked>
      <name>TIPWebAPI_Bearer</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
